use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

use crate::agent_registry::AgentRegistryEntry;
use agent_api::AgentWrapperCapabilities;
use clap::Parser;

#[cfg(test)]
use crate::agent_registry::AgentRegistry;
#[cfg(test)]
use crate::capability_projection::{
    resolve_capability_publication_target, CapabilityPublicationTarget,
};
#[cfg(test)]
use serde::Deserialize;

#[cfg(not(test))]
use crate::capability_publication as capability_publication_mod;
#[cfg(test)]
use xtask::capability_publication as capability_publication_mod;

pub const DEFAULT_OUT_PATH: &str = "docs/specs/unified-agent-api/capability-matrix.md";

#[derive(Debug, Parser)]
pub struct Args {
    /// Verify the checked-in capability matrix without rewriting it.
    #[arg(long, conflicts_with = "out")]
    pub check: bool,

    /// Write the generated markdown to this path. Defaults to the workspace-root capability matrix path when omitted.
    #[arg(long)]
    pub out: Option<PathBuf>,
}

pub fn run(args: Args) -> Result<(), String> {
    let markdown = generate_markdown()?;
    if args.check {
        let checked_in = resolve_output_path(None)?;
        validate_checked_in_file(&checked_in, &markdown)?;
    } else {
        let out = resolve_output_path(args.out.as_deref())?;
        write_file(&out, &markdown)?;
    }
    Ok(())
}

pub fn collect_builtin_backend_capabilities(
) -> Result<BTreeMap<String, AgentWrapperCapabilities>, String> {
    capability_publication_mod::collect_published_backend_capabilities(&resolve_workspace_root()?)
}

pub fn validate_agent_publication_continuity(
    workspace_root: &Path,
    entry: &AgentRegistryEntry,
) -> Result<(), String> {
    capability_publication_mod::validate_agent_publication_continuity(workspace_root, entry)
}

pub fn generate_markdown() -> Result<String, String> {
    let inventory =
        capability_publication_mod::collect_capability_publication_inventory(&resolve_workspace_root()?)?;
    Ok(render_matrix(
        &inventory.backends,
        &inventory.canonical_target_header,
    ))
}

fn write_file(path: &Path, contents: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|err| format!("create_dir_all({path:?}): {err}"))?;
    }
    fs::write(path, contents).map_err(|err| format!("write({path:?}): {err}"))?;
    Ok(())
}

fn validate_checked_in_file(path: &Path, contents: &str) -> Result<(), String> {
    let checked_in = fs::read_to_string(path).map_err(|err| format!("read({path:?}): {err}"))?;
    if checked_in == contents {
        return Ok(());
    }

    Err(format!(
        "{} is stale; regenerate with `cargo run -p xtask -- capability-matrix`",
        path.display()
    ))
}

fn render_matrix(
    backends: &BTreeMap<String, AgentWrapperCapabilities>,
    canonical_target_header: &str,
) -> String {
    let backend_ids: Vec<String> = backends.keys().cloned().collect();

    let mut all_caps = BTreeSet::<String>::new();
    for caps in backends.values() {
        all_caps.extend(caps.ids.iter().cloned());
    }

    let mut buckets = BTreeMap::<String, Vec<String>>::new();
    for cap in all_caps {
        let bucket = bucket_for(&cap);
        buckets.entry(bucket).or_default().push(cap);
    }

    for caps in buckets.values_mut() {
        caps.sort();
        caps.dedup();
    }

    let mut out = String::new();
    out.push_str("# Capability matrix — Unified Agent API\n\n");
    out.push_str("Status: Approved  \n");
    out.push_str("Approved (UTC): 2026-02-21\n\n");
    out.push_str("This file is generated by `cargo run -p xtask -- capability-matrix`.\n");
    out.push_str(canonical_target_header);
    out.push_str("This inventory documents backend capability advertising, not support or promotion status.\n");
    out.push_str("Do not edit by hand.\n\n");

    let bucket_order = bucket_order(&backend_ids);
    for bucket in bucket_order {
        let Some(cap_ids) = buckets.get(&bucket) else {
            continue;
        };
        if cap_ids.is_empty() {
            continue;
        }

        out.push_str(&format!("## `{bucket}`\n\n"));
        out.push_str("| capability id |");
        for backend_id in backend_ids.iter() {
            out.push_str(&format!(" `{backend_id}` |"));
        }
        out.push('\n');

        out.push_str("|---|");
        for _ in backend_ids.iter() {
            out.push_str("---|");
        }
        out.push('\n');

        for cap_id in cap_ids.iter() {
            out.push_str(&format!("| `{cap_id}` |"));
            for backend_id in backend_ids.iter() {
                let supported = backends
                    .get(backend_id)
                    .is_some_and(|caps| caps.contains(cap_id));
                out.push_str(if supported { " ✅ |" } else { " — |" });
            }
            out.push('\n');
        }
        out.push('\n');
    }

    out
}

fn bucket_for(capability_id: &str) -> String {
    if capability_id == "agent_api.run" || capability_id == "agent_api.events" {
        return "agent_api.core".to_string();
    }

    if capability_id == "agent_api.events" || capability_id.starts_with("agent_api.events.") {
        return "agent_api.events".to_string();
    }

    if capability_id.starts_with("agent_api.exec.") {
        return "agent_api.exec".to_string();
    }

    if capability_id.starts_with("agent_api.session.") {
        return "agent_api.session".to_string();
    }

    for prefix in [
        "agent_api.tools.",
        "agent_api.artifacts.",
        "agent_api.control.",
        "agent_api.config.",
    ] {
        if capability_id.starts_with(prefix) {
            let bucket = prefix.trim_end_matches('.');
            return bucket.to_string();
        }
    }

    if capability_id.starts_with("agent_api.") {
        return "agent_api.other".to_string();
    }

    if let Some(agent_kind) = capability_id.strip_prefix("backend.") {
        let agent_kind = agent_kind
            .split_once('.')
            .map(|(head, _)| head)
            .unwrap_or(agent_kind);
        return format!("backend.{agent_kind}");
    }

    "other".to_string()
}

fn bucket_order(backend_ids: &[String]) -> Vec<String> {
    let mut out = Vec::new();
    out.extend([
        "agent_api.core".to_string(),
        "agent_api.events".to_string(),
        "agent_api.exec".to_string(),
        "agent_api.session".to_string(),
        "agent_api.tools".to_string(),
        "agent_api.artifacts".to_string(),
        "agent_api.control".to_string(),
        "agent_api.config".to_string(),
        "agent_api.other".to_string(),
    ]);

    let mut backend_buckets: Vec<String> = backend_ids
        .iter()
        .map(|id| format!("backend.{id}"))
        .collect();
    backend_buckets.sort();
    backend_buckets.dedup();
    out.extend(backend_buckets);

    out.push("other".to_string());
    out
}

#[cfg(test)]
fn command_available_on_target(manifest: &UnionManifest, path: &[&str], target: &str) -> bool {
    capability_publication_mod::manifest_command_available_on_target(
        &manifest.as_publication_manifest(),
        path,
        target,
    )
}

fn resolve_output_path(explicit: Option<&Path>) -> Result<PathBuf, String> {
    match explicit {
        Some(path) => Ok(path.to_path_buf()),
        None => Ok(resolve_workspace_root()?.join(Path::new(DEFAULT_OUT_PATH))),
    }
}

fn resolve_workspace_root() -> Result<PathBuf, String> {
    let current_dir = std::env::current_dir().map_err(|err| format!("current_dir: {err}"))?;
    for candidate in current_dir.ancestors() {
        let cargo_toml = candidate.join("Cargo.toml");
        let Ok(text) = fs::read_to_string(&cargo_toml) else {
            continue;
        };
        if text.contains("[workspace]") {
            return Ok(candidate.to_path_buf());
        }
    }

    Err(format!(
        "could not resolve workspace root from {}",
        current_dir.display()
    ))
}

#[cfg(test)]
fn runtime_backend_capabilities(
    agent_id: &str,
) -> Result<(String, AgentWrapperCapabilities), String> {
    capability_publication_mod::collect_agent_capabilities(&resolve_workspace_root()?, agent_id)
        .map(|capabilities| (agent_id.to_string(), capabilities))
}

#[cfg(test)]
fn projected_advertised_capabilities(
    registry_entry: &AgentRegistryEntry,
    manifest: &UnionManifest,
) -> Result<BTreeSet<String>, String> {
    capability_publication_mod::project_manifest_advertised_capabilities(
        registry_entry,
        &manifest.as_publication_manifest(),
    )
}

#[cfg(test)]
fn validate_capability_publication_target(
    registry_entry: &AgentRegistryEntry,
    manifest: &UnionManifest,
) -> Result<(), String> {
    capability_publication_mod::validate_capability_publication_target(
        registry_entry,
        &manifest.as_publication_manifest(),
    )
}

#[cfg(test)]
fn render_publication_target_description(
    registry_entry: &AgentRegistryEntry,
) -> Result<String, String> {
    capability_publication_mod::render_publication_target_description(registry_entry)
}

#[cfg(test)]
fn render_canonical_target_header(entries: &[&AgentRegistryEntry]) -> Result<String, String> {
    let mut canonical_targets = Vec::<String>::new();
    let mut default_backends = Vec::<String>::new();

    for entry in entries.iter().copied() {
        match resolve_capability_publication_target(entry)? {
            CapabilityPublicationTarget::Explicit(target) => {
                canonical_targets.push(format!("`{}={target}`", entry.agent_id));
            }
            CapabilityPublicationTarget::DefaultBuiltInConfig => {
                default_backends.push(format!("`{}`", entry.agent_id));
            }
        }
    }

    let mut out = String::from("Canonical target profile: ");
    if !canonical_targets.is_empty() {
        out.push_str(&canonical_targets.join(", "));
    }
    if !canonical_targets.is_empty() && !default_backends.is_empty() {
        out.push_str("; ");
    }
    if !default_backends.is_empty() {
        out.push_str(&default_backends.join(", "));
        out.push(' ');
        out.push_str(if default_backends.len() == 1 {
            "uses"
        } else {
            "use"
        });
        out.push_str(" the default built-in backend config");
    }
    out.push_str(".\n");
    Ok(out)
}

#[cfg(test)]
#[derive(Debug, Deserialize)]
struct UnionManifest {
    #[serde(default)]
    expected_targets: Vec<String>,
    commands: Vec<UnionCommand>,
}

#[cfg(test)]
#[derive(Debug, Deserialize)]
struct UnionCommand {
    path: Vec<String>,
    available_on: Vec<String>,
}

#[cfg(test)]
impl UnionManifest {
    fn as_publication_manifest(&self) -> capability_publication_mod::ManifestCurrent {
        capability_publication_mod::ManifestCurrent {
            expected_targets: self.expected_targets.clone(),
            commands: self
                .commands
                .iter()
                .map(|command| capability_publication_mod::ManifestCommand {
                    path: command.path.clone(),
                    available_on: command.available_on.clone(),
                })
                .collect(),
        }
    }
}
