use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

use agent_api::{
    backends::{
        claude_code::{ClaudeCodeBackend, ClaudeCodeBackendConfig},
        codex::{CodexBackend, CodexBackendConfig},
    },
    AgentWrapperBackend, AgentWrapperCapabilities,
};
use clap::Parser;
use serde::Deserialize;

const CODEX_MANIFEST_PATH: &str = "cli_manifests/codex/current.json";
const CLAUDE_MANIFEST_PATH: &str = "cli_manifests/claude_code/current.json";
const DEFAULT_OUT_PATH: &str = "docs/specs/unified-agent-api/capability-matrix.md";
const CODEX_CANONICAL_TARGET: &str = "x86_64-unknown-linux-musl";
const CLAUDE_CANONICAL_TARGET: &str = "linux-x64";

const CAPABILITY_MCP_LIST_V1: &str = "agent_api.tools.mcp.list.v1";
const CAPABILITY_MCP_GET_V1: &str = "agent_api.tools.mcp.get.v1";
const CAPABILITY_MCP_ADD_V1: &str = "agent_api.tools.mcp.add.v1";
const CAPABILITY_MCP_REMOVE_V1: &str = "agent_api.tools.mcp.remove.v1";

#[derive(Debug, Parser)]
pub struct Args {
    /// Write the generated markdown to this path. Defaults to the workspace-root capability matrix path when omitted.
    #[arg(long)]
    pub out: Option<PathBuf>,
}

pub fn run(args: Args) -> Result<(), String> {
    let backends = collect_builtin_backend_capabilities()?;
    let markdown = render_matrix(&backends);
    let out = resolve_output_path(args.out.as_deref());
    write_file(&out, &markdown)?;
    Ok(())
}

pub(crate) fn collect_builtin_backend_capabilities(
) -> Result<BTreeMap<String, AgentWrapperCapabilities>, String> {
    let mut backends = BTreeMap::<String, AgentWrapperCapabilities>::new();

    let codex = CodexBackend::new(CodexBackendConfig::default());
    backends.insert(codex.kind().as_str().to_string(), codex.capabilities());

    let claude = ClaudeCodeBackend::new(ClaudeCodeBackendConfig::default());
    backends.insert(claude.kind().as_str().to_string(), claude.capabilities());

    apply_canonical_builtin_target_profile(&mut backends)?;

    Ok(backends)
}

fn write_file(path: &Path, contents: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|err| format!("create_dir_all({path:?}): {err}"))?;
    }
    fs::write(path, contents).map_err(|err| format!("write({path:?}): {err}"))?;
    Ok(())
}

fn render_matrix(backends: &BTreeMap<String, AgentWrapperCapabilities>) -> String {
    let backend_ids: Vec<String> = backends.keys().cloned().collect();

    let mut all_caps = BTreeSet::<String>::new();
    for caps in backends.values() {
        all_caps.extend(caps.ids.iter().cloned());
    }

    let mut buckets = BTreeMap::<String, Vec<String>>::new();
    for cap in all_caps {
        let bucket = bucket_for(&cap);
        buckets.entry(bucket).or_default().push(cap);
    }

    for caps in buckets.values_mut() {
        caps.sort();
        caps.dedup();
    }

    let mut out = String::new();
    out.push_str("# Capability matrix — Unified Agent API\n\n");
    out.push_str("Status: Approved  \n");
    out.push_str("Approved (UTC): 2026-02-21\n\n");
    out.push_str("This file is generated by `cargo run -p xtask -- capability-matrix`.\n");
    out.push_str(&format!(
        "Canonical target profile: `codex={CODEX_CANONICAL_TARGET}`, `claude_code={CLAUDE_CANONICAL_TARGET}`.\n"
    ));
    out.push_str("Do not edit by hand.\n\n");

    let bucket_order = bucket_order(&backend_ids);
    for bucket in bucket_order {
        let Some(cap_ids) = buckets.get(&bucket) else {
            continue;
        };
        if cap_ids.is_empty() {
            continue;
        }

        out.push_str(&format!("## `{bucket}`\n\n"));
        out.push_str("| capability id |");
        for backend_id in backend_ids.iter() {
            out.push_str(&format!(" `{backend_id}` |"));
        }
        out.push('\n');

        out.push_str("|---|");
        for _ in backend_ids.iter() {
            out.push_str("---|");
        }
        out.push('\n');

        for cap_id in cap_ids.iter() {
            out.push_str(&format!("| `{cap_id}` |"));
            for backend_id in backend_ids.iter() {
                let supported = backends
                    .get(backend_id)
                    .is_some_and(|caps| caps.contains(cap_id));
                out.push_str(if supported { " ✅ |" } else { " — |" });
            }
            out.push('\n');
        }
        out.push('\n');
    }

    out
}

fn bucket_for(capability_id: &str) -> String {
    if capability_id == "agent_api.run" || capability_id == "agent_api.events" {
        return "agent_api.core".to_string();
    }

    if capability_id == "agent_api.events" || capability_id.starts_with("agent_api.events.") {
        return "agent_api.events".to_string();
    }

    if capability_id.starts_with("agent_api.exec.") {
        return "agent_api.exec".to_string();
    }

    if capability_id.starts_with("agent_api.session.") {
        return "agent_api.session".to_string();
    }

    for prefix in [
        "agent_api.tools.",
        "agent_api.artifacts.",
        "agent_api.control.",
        "agent_api.config.",
    ] {
        if capability_id.starts_with(prefix) {
            let bucket = prefix.trim_end_matches('.');
            return bucket.to_string();
        }
    }

    if capability_id.starts_with("agent_api.") {
        return "agent_api.other".to_string();
    }

    if let Some(agent_kind) = capability_id.strip_prefix("backend.") {
        let agent_kind = agent_kind
            .split_once('.')
            .map(|(head, _)| head)
            .unwrap_or(agent_kind);
        return format!("backend.{agent_kind}");
    }

    "other".to_string()
}

fn bucket_order(backend_ids: &[String]) -> Vec<String> {
    let mut out = Vec::new();
    out.extend([
        "agent_api.core".to_string(),
        "agent_api.events".to_string(),
        "agent_api.exec".to_string(),
        "agent_api.session".to_string(),
        "agent_api.tools".to_string(),
        "agent_api.artifacts".to_string(),
        "agent_api.control".to_string(),
        "agent_api.config".to_string(),
        "agent_api.other".to_string(),
    ]);

    let mut backend_buckets: Vec<String> = backend_ids
        .iter()
        .map(|id| format!("backend.{id}"))
        .collect();
    backend_buckets.sort();
    backend_buckets.dedup();
    out.extend(backend_buckets);

    out.push("other".to_string());
    out
}

fn apply_canonical_builtin_target_profile(
    backends: &mut BTreeMap<String, AgentWrapperCapabilities>,
) -> Result<(), String> {
    let codex_manifest =
        read_union_manifest(&resolve_workspace_path(Path::new(CODEX_MANIFEST_PATH)))?;
    let claude_manifest =
        read_union_manifest(&resolve_workspace_path(Path::new(CLAUDE_MANIFEST_PATH)))?;

    let codex_caps = backends
        .get_mut("codex")
        .ok_or_else(|| "missing built-in backend capabilities for codex".to_string())?;
    apply_manifest_mcp_projection(codex_caps, &codex_manifest, CODEX_CANONICAL_TARGET);

    let claude_caps = backends
        .get_mut("claude_code")
        .ok_or_else(|| "missing built-in backend capabilities for claude_code".to_string())?;
    apply_manifest_mcp_projection(claude_caps, &claude_manifest, CLAUDE_CANONICAL_TARGET);

    Ok(())
}

fn apply_manifest_mcp_projection(
    capabilities: &mut AgentWrapperCapabilities,
    manifest: &UnionManifest,
    target: &str,
) {
    sync_capability_from_manifest(
        capabilities,
        CAPABILITY_MCP_LIST_V1,
        command_available_on_target(manifest, &["mcp", "list"], target),
        true,
    );
    sync_capability_from_manifest(
        capabilities,
        CAPABILITY_MCP_GET_V1,
        command_available_on_target(manifest, &["mcp", "get"], target),
        true,
    );
    sync_capability_from_manifest(
        capabilities,
        CAPABILITY_MCP_ADD_V1,
        command_available_on_target(manifest, &["mcp", "add"], target),
        false,
    );
    sync_capability_from_manifest(
        capabilities,
        CAPABILITY_MCP_REMOVE_V1,
        command_available_on_target(manifest, &["mcp", "remove"], target),
        false,
    );
}

fn sync_capability_from_manifest(
    capabilities: &mut AgentWrapperCapabilities,
    capability_id: &str,
    available_on_canonical_target: bool,
    advertise_when_available: bool,
) {
    if available_on_canonical_target {
        if advertise_when_available {
            capabilities.ids.insert(capability_id.to_string());
        }
        return;
    }

    capabilities.ids.remove(capability_id);
}

fn command_available_on_target(manifest: &UnionManifest, path: &[&str], target: &str) -> bool {
    manifest
        .commands
        .iter()
        .find(|command| {
            command
                .path
                .iter()
                .map(String::as_str)
                .eq(path.iter().copied())
        })
        .is_some_and(|command| command.available_on.iter().any(|item| item == target))
}

fn resolve_output_path(explicit: Option<&Path>) -> PathBuf {
    match explicit {
        Some(path) => path.to_path_buf(),
        None => resolve_workspace_path(Path::new(DEFAULT_OUT_PATH)),
    }
}

fn resolve_workspace_path(path: &Path) -> PathBuf {
    workspace_root().join(path)
}

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("CARGO_MANIFEST_DIR has crates/xtask parent structure")
        .to_path_buf()
}

fn read_union_manifest(path: &Path) -> Result<UnionManifest, String> {
    let text = fs::read_to_string(path).map_err(|err| format!("read({path:?}): {err}"))?;
    serde_json::from_str(&text).map_err(|err| format!("parse({path:?}): {err}"))
}

#[derive(Debug, Deserialize)]
struct UnionManifest {
    commands: Vec<UnionCommand>,
}

#[derive(Debug, Deserialize)]
struct UnionCommand {
    path: Vec<String>,
    available_on: Vec<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn manifest_with_commands(commands: &[(&[&str], &[&str])]) -> UnionManifest {
        UnionManifest {
            commands: commands
                .iter()
                .map(|(path, available_on)| UnionCommand {
                    path: path.iter().map(|segment| (*segment).to_string()).collect(),
                    available_on: available_on
                        .iter()
                        .map(|target| (*target).to_string())
                        .collect(),
                })
                .collect(),
        }
    }

    #[test]
    fn command_available_on_target_matches_exact_path_and_target() {
        let manifest = manifest_with_commands(&[
            (&["mcp", "list"], &["linux-x64"]),
            (&["mcp", "get"], &["win32-x64"]),
        ]);

        assert!(command_available_on_target(
            &manifest,
            &["mcp", "list"],
            "linux-x64"
        ));
        assert!(!command_available_on_target(
            &manifest,
            &["mcp"],
            "linux-x64"
        ));
        assert!(!command_available_on_target(
            &manifest,
            &["mcp", "get"],
            "linux-x64"
        ));
    }

    #[test]
    fn manifest_projection_adds_read_caps_and_clears_unavailable_caps() {
        let manifest = manifest_with_commands(&[
            (&["mcp", "list"], &["linux-x64"]),
            (&["mcp", "get"], &["linux-x64"]),
        ]);
        let mut capabilities = AgentWrapperCapabilities {
            ids: [
                CAPABILITY_MCP_ADD_V1.to_string(),
                CAPABILITY_MCP_REMOVE_V1.to_string(),
            ]
            .into_iter()
            .collect(),
        };

        apply_manifest_mcp_projection(&mut capabilities, &manifest, "linux-x64");

        assert!(capabilities.contains(CAPABILITY_MCP_LIST_V1));
        assert!(capabilities.contains(CAPABILITY_MCP_GET_V1));
        assert!(!capabilities.contains(CAPABILITY_MCP_ADD_V1));
        assert!(!capabilities.contains(CAPABILITY_MCP_REMOVE_V1));
    }

    #[test]
    fn resolve_output_path_defaults_to_workspace_root() {
        assert_eq!(
            resolve_output_path(None),
            workspace_root().join(DEFAULT_OUT_PATH)
        );
    }

    #[test]
    fn resolve_output_path_preserves_absolute_path() {
        let absolute = std::env::temp_dir().join("capability-matrix-absolute.md");
        assert_eq!(resolve_output_path(Some(absolute.as_path())), absolute);
    }

    #[test]
    fn resolve_output_path_preserves_explicit_relative_path() {
        let relative = Path::new("tmp/capability-matrix.md");
        assert_eq!(resolve_output_path(Some(relative)), relative);
    }
}
