use std::{
    cmp::Ordering,
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

use clap::Parser;
use semver::Version;
use serde::{Deserialize, Serialize};

use crate::wrapper_coverage_shared::RootIntakeLayout;

const CURRENT_AGENT_ROOTS: [(&str, &str); 2] = [
    ("codex", "cli_manifests/codex"),
    ("claude_code", "cli_manifests/claude_code"),
];
const JSON_OUTPUT_PATH: &str = "cli_manifests/support_matrix/current.json";
const MARKDOWN_OUTPUT_PATH: &str = "docs/specs/unified-agent-api/support-matrix.md";
const GENERATED_SECTION_TITLE: &str = "## Published support matrix";
const GENERATED_SECTION_NOTE: &str =
    "This section is generated by `cargo run -p xtask -- support-matrix`.\nDo not edit this section by hand.";
const GENERATED_START_MARKER: &str = "<!-- support-matrix-published:start -->";
const GENERATED_END_MARKER: &str = "<!-- support-matrix-published:end -->";

#[derive(Debug, Parser)]
pub struct Args {}

pub fn run(_args: Args) -> Result<(), String> {
    let workspace_root = resolve_workspace_root()?;
    let rows = derive_rows(&workspace_root)?;
    let bundle = render_publication_bundle(&rows)?;
    write_publication_artifacts(&workspace_root, &bundle)?;
    Ok(())
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SupportRow {
    pub agent: String,
    pub version: String,
    pub target: String,
    pub manifest_support: ManifestSupportState,
    pub backend_support: BackendSupportState,
    pub uaa_support: UaaSupportState,
    pub pointer_promotion: PointerPromotionState,
    #[serde(default)]
    pub evidence_notes: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ManifestSupportState {
    Supported,
    Unsupported,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BackendSupportState {
    Supported,
    Partial,
    Unsupported,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum UaaSupportState {
    Supported,
    Partial,
    Unsupported,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PointerPromotionState {
    None,
    LatestSupported,
    LatestValidated,
    LatestSupportedAndValidated,
}

#[derive(Debug, Clone)]
struct AgentRoot {
    agent: String,
    root: PathBuf,
}

#[derive(Debug, Deserialize)]
struct CurrentUnion {
    #[serde(default)]
    expected_targets: Vec<String>,
    #[serde(default)]
    inputs: Vec<CurrentUnionInput>,
}

#[derive(Debug, Deserialize)]
struct CurrentUnionInput {
    target_triple: String,
    #[serde(default)]
    binary: CurrentUnionBinary,
}

#[derive(Debug, Default, Deserialize)]
struct CurrentUnionBinary {
    semantic_version: Option<String>,
}

#[derive(Debug, Deserialize)]
struct VersionMetadata {
    semantic_version: String,
    coverage: VersionCoverage,
}

#[derive(Debug, Deserialize)]
struct VersionCoverage {
    #[serde(default)]
    supported_targets: Vec<String>,
}

#[derive(Debug, Default, Deserialize)]
struct SupportReport {
    #[serde(default)]
    inputs: SupportReportInputs,
    #[serde(default)]
    deltas: SupportReportDeltas,
}

#[derive(Debug, Default, Deserialize)]
struct SupportReportInputs {
    #[serde(default)]
    upstream: SupportReportUpstream,
}

#[derive(Debug, Default, Deserialize)]
struct SupportReportUpstream {
    #[serde(default)]
    targets: Vec<String>,
}

#[derive(Debug, Default, Deserialize)]
struct SupportReportDeltas {
    #[serde(default)]
    missing_commands: Vec<serde_json::Value>,
    #[serde(default)]
    missing_flags: Vec<serde_json::Value>,
    #[serde(default)]
    missing_args: Vec<serde_json::Value>,
    #[serde(default)]
    intentionally_unsupported: Vec<serde_json::Value>,
    #[serde(default)]
    wrapper_only_commands: Vec<serde_json::Value>,
    #[serde(default)]
    wrapper_only_flags: Vec<serde_json::Value>,
    #[serde(default)]
    wrapper_only_args: Vec<serde_json::Value>,
}

#[derive(Debug, Clone)]
struct CurrentRootPosture {
    expected_targets: Vec<String>,
    current_version: Option<String>,
    current_targets: BTreeSet<String>,
}

#[derive(Debug, Clone)]
struct PointerSet {
    latest_supported: BTreeMap<String, Option<String>>,
    latest_validated: BTreeMap<String, Option<String>>,
}

#[derive(Debug, Clone)]
struct PublicationBundle {
    json: String,
    markdown: String,
}

#[derive(Debug, Serialize)]
struct SupportMatrixArtifact<'a> {
    schema_version: u8,
    rows: &'a [SupportRow],
}

pub(crate) fn derive_rows(workspace_root: &Path) -> Result<Vec<SupportRow>, String> {
    let roots = CURRENT_AGENT_ROOTS
        .iter()
        .map(|(agent, rel_root)| AgentRoot {
            agent: (*agent).to_string(),
            root: workspace_root.join(rel_root),
        })
        .collect::<Vec<_>>();
    derive_rows_for_roots(&roots)
}

fn derive_rows_for_roots(roots: &[AgentRoot]) -> Result<Vec<SupportRow>, String> {
    let mut rows = Vec::new();
    for root in roots {
        rows.extend(derive_rows_for_root(root)?);
    }

    rows.sort_by(|left, right| compare_rows(left, right));
    Ok(rows)
}

fn derive_rows_for_root(root: &AgentRoot) -> Result<Vec<SupportRow>, String> {
    let posture = read_current_root_posture(&root.root)?;
    let pointers = read_pointers(&root.root, &posture.expected_targets)?;
    let layout = RootIntakeLayout::new(root.root.clone());

    let mut rows = Vec::new();
    let versions_dir = layout.versions_dir();
    for entry in fs::read_dir(&versions_dir)
        .map_err(|err| format!("read_dir({}): {err}", versions_dir.display()))?
    {
        let entry = entry.map_err(|err| format!("read_dir entry error: {err}"))?;
        let path = entry.path();
        if path.extension().and_then(|ext| ext.to_str()) != Some("json") {
            continue;
        }

        let metadata: VersionMetadata = read_json(&path)?;
        let supported_targets = metadata
            .coverage
            .supported_targets
            .into_iter()
            .collect::<BTreeSet<_>>();

        for target in posture.expected_targets.iter() {
            let manifest_support = if supported_targets.contains(target) {
                ManifestSupportState::Supported
            } else {
                ManifestSupportState::Unsupported
            };

            let report = load_support_report(&layout, &metadata.semantic_version, target)?;
            let backend_support = classify_backend_support(report.as_ref());
            let pointer_promotion =
                classify_pointer_promotion(&pointers, target, &metadata.semantic_version);
            let evidence_notes = build_evidence_notes(
                report.as_ref(),
                &posture,
                target,
                &metadata.semantic_version,
            );
            let uaa_support =
                classify_uaa_support(manifest_support, backend_support, &evidence_notes);

            rows.push(SupportRow {
                agent: root.agent.clone(),
                version: metadata.semantic_version.clone(),
                target: target.clone(),
                manifest_support,
                backend_support,
                uaa_support,
                pointer_promotion,
                evidence_notes,
            });
        }
    }

    Ok(rows)
}

fn read_current_root_posture(root: &Path) -> Result<CurrentRootPosture, String> {
    let current_path = root.join("current.json");
    let current: CurrentUnion = read_json(&current_path)?;
    if current.expected_targets.is_empty() {
        return Err(format!(
            "{}: expected_targets must not be empty",
            current_path.display()
        ));
    }

    let mut versions = BTreeSet::new();
    let current_targets = current
        .inputs
        .iter()
        .map(|input| {
            if let Some(version) = input.binary.semantic_version.clone() {
                versions.insert(version);
            }
            input.target_triple.clone()
        })
        .collect::<BTreeSet<_>>();

    let current_version = match versions.len() {
        0 => None,
        1 => versions.into_iter().next(),
        _ => {
            return Err(format!(
                "{}: current.json contained multiple semantic versions",
                current_path.display()
            ));
        }
    };

    Ok(CurrentRootPosture {
        expected_targets: current.expected_targets,
        current_version,
        current_targets,
    })
}

fn read_pointers(root: &Path, expected_targets: &[String]) -> Result<PointerSet, String> {
    let layout = RootIntakeLayout::new(root.to_path_buf());
    let mut latest_supported = BTreeMap::new();
    let mut latest_validated = BTreeMap::new();

    for target in expected_targets {
        latest_supported.insert(
            target.clone(),
            read_pointer_file(&layout.latest_supported_pointer_path(target))?,
        );
        latest_validated.insert(
            target.clone(),
            read_pointer_file(&layout.latest_validated_pointer_path(target))?,
        );
    }

    Ok(PointerSet {
        latest_supported,
        latest_validated,
    })
}

fn read_pointer_file(path: &Path) -> Result<Option<String>, String> {
    let raw = fs::read_to_string(path).map_err(|err| format!("read({}): {err}", path.display()))?;
    let value = raw.trim();
    if value.is_empty() || value == "none" {
        Ok(None)
    } else {
        Ok(Some(value.to_string()))
    }
}

fn load_support_report(
    layout: &RootIntakeLayout,
    version: &str,
    target: &str,
) -> Result<Option<SupportReport>, String> {
    let version_dir = layout.reports_version_dir(version);
    let exact_target = version_dir.join(format!("coverage.{target}.json"));
    if exact_target.exists() {
        return read_json(&exact_target).map(Some);
    }

    for candidate in [version_dir.join("coverage.any.json"), version_dir.join("coverage.all.json")]
    {
        if !candidate.exists() {
            continue;
        }

        let report: SupportReport = read_json(&candidate)?;
        if report_mentions_target(&report, target) {
            return Ok(Some(report));
        }
    }
    Ok(None)
}

fn report_mentions_target(report: &SupportReport, target: &str) -> bool {
    report.inputs.upstream.targets.is_empty()
        || report
            .inputs
            .upstream
            .targets
            .iter()
            .any(|candidate| candidate == target)
}

fn classify_backend_support(report: Option<&SupportReport>) -> BackendSupportState {
    let Some(report) = report else {
        return BackendSupportState::Unsupported;
    };

    if report_has_missing_surface(report) {
        return BackendSupportState::Unsupported;
    }

    if report_has_partial_caveat(report) {
        return BackendSupportState::Partial;
    }

    BackendSupportState::Supported
}

fn report_has_missing_surface(report: &SupportReport) -> bool {
    !report.deltas.missing_commands.is_empty()
        || !report.deltas.missing_flags.is_empty()
        || !report.deltas.missing_args.is_empty()
}

fn report_has_partial_caveat(report: &SupportReport) -> bool {
    !report.deltas.intentionally_unsupported.is_empty()
        || !report.deltas.wrapper_only_commands.is_empty()
        || !report.deltas.wrapper_only_flags.is_empty()
        || !report.deltas.wrapper_only_args.is_empty()
}

fn classify_pointer_promotion(
    pointers: &PointerSet,
    target: &str,
    version: &str,
) -> PointerPromotionState {
    let latest_supported = pointers
        .latest_supported
        .get(target)
        .and_then(|value| value.as_deref())
        == Some(version);
    let latest_validated = pointers
        .latest_validated
        .get(target)
        .and_then(|value| value.as_deref())
        == Some(version);

    match (latest_supported, latest_validated) {
        (true, true) => PointerPromotionState::LatestSupportedAndValidated,
        (true, false) => PointerPromotionState::LatestSupported,
        (false, true) => PointerPromotionState::LatestValidated,
        (false, false) => PointerPromotionState::None,
    }
}

fn build_evidence_notes(
    report: Option<&SupportReport>,
    posture: &CurrentRootPosture,
    target: &str,
    version: &str,
) -> Vec<String> {
    let mut notes = Vec::new();

    if let Some(report) = report {
        if !report.deltas.intentionally_unsupported.is_empty() {
            notes.push(
                "backend report includes intentionally unsupported surface outside unified support"
                    .to_string(),
            );
        }
        if !report.deltas.wrapper_only_commands.is_empty()
            || !report.deltas.wrapper_only_flags.is_empty()
            || !report.deltas.wrapper_only_args.is_empty()
        {
            notes.push("backend report includes backend-only surface outside unified support".to_string());
        }
    }

    if posture.current_version.as_deref() == Some(version) && !posture.current_targets.contains(target)
    {
        notes.push("current root snapshot omits this target".to_string());
    }

    notes
}

fn classify_uaa_support(
    manifest_support: ManifestSupportState,
    backend_support: BackendSupportState,
    evidence_notes: &[String],
) -> UaaSupportState {
    match (manifest_support, backend_support) {
        (ManifestSupportState::Supported, BackendSupportState::Supported)
            if evidence_notes.is_empty() =>
        {
            UaaSupportState::Supported
        }
        (ManifestSupportState::Supported, BackendSupportState::Unsupported)
        | (ManifestSupportState::Unsupported, BackendSupportState::Supported)
        | (ManifestSupportState::Unsupported, BackendSupportState::Unsupported) => {
            UaaSupportState::Unsupported
        }
        _ => UaaSupportState::Partial,
    }
}

fn compare_rows(left: &SupportRow, right: &SupportRow) -> Ordering {
    left.agent
        .cmp(&right.agent)
        .then_with(|| left.target.cmp(&right.target))
        .then_with(|| compare_semver_desc(&left.version, &right.version))
}

fn compare_semver_desc(left: &str, right: &str) -> Ordering {
    match (Version::parse(left), Version::parse(right)) {
        (Ok(left), Ok(right)) => right.cmp(&left),
        _ => right.cmp(left),
    }
}

fn read_json<T>(path: &Path) -> Result<T, String>
where
    T: for<'de> Deserialize<'de>,
{
    let text = fs::read_to_string(path).map_err(|err| format!("read({}): {err}", path.display()))?;
    serde_json::from_str(&text).map_err(|err| format!("parse({}): {err}", path.display()))
}

fn render_publication_bundle(rows: &[SupportRow]) -> Result<PublicationBundle, String> {
    let json = serde_json::to_string_pretty(&SupportMatrixArtifact {
        schema_version: 1,
        rows,
    })
    .map_err(|err| format!("serialize support-matrix json: {err}"))?;
    let markdown = render_markdown_projection(rows);

    Ok(PublicationBundle {
        json: format!("{json}\n"),
        markdown,
    })
}

fn render_markdown_projection(rows: &[SupportRow]) -> String {
    let mut out = String::new();
    let mut current_agent: Option<&str> = None;

    for row in rows {
        if current_agent != Some(row.agent.as_str()) {
            if current_agent.is_some() {
                out.push('\n');
            }
            current_agent = Some(row.agent.as_str());
            out.push_str(&format!("### `{}`\n\n", row.agent));
            out.push_str("| agent | target | version | manifest_support | backend_support | uaa_support | pointer_promotion | evidence_notes |\n");
            out.push_str("|---|---|---|---|---|---|---|---|\n");
        }

        let notes = if row.evidence_notes.is_empty() {
            "—".to_string()
        } else {
            row.evidence_notes.join("; ")
        };

        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | `{}` | `{}` | `{}` | `{}` | {} |\n",
            row.agent,
            row.target,
            row.version,
            row.manifest_support.as_str(),
            row.backend_support.as_str(),
            row.uaa_support.as_str(),
            row.pointer_promotion.as_str(),
            notes
        ));
    }

    out
}

fn write_publication_artifacts(
    workspace_root: &Path,
    bundle: &PublicationBundle,
) -> Result<(), String> {
    let json_path = workspace_root.join(JSON_OUTPUT_PATH);
    let markdown_path = workspace_root.join(MARKDOWN_OUTPUT_PATH);
    write_file(&json_path, &bundle.json)?;

    let existing_markdown = fs::read_to_string(&markdown_path)
        .map_err(|err| format!("read({}): {err}", markdown_path.display()))?;
    let updated_markdown = splice_markdown_projection(&existing_markdown, &bundle.markdown);
    write_file(&markdown_path, &updated_markdown)?;
    Ok(())
}

fn write_file(path: &Path, contents: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|err| format!("create_dir_all({}): {err}", parent.display()))?;
    }
    fs::write(path, contents).map_err(|err| format!("write({}): {err}", path.display()))
}

fn splice_markdown_projection(existing: &str, projection: &str) -> String {
    let generated_block = format!(
        "{GENERATED_START_MARKER}\n{projection}{GENERATED_END_MARKER}"
    );

    match (
        existing.find(GENERATED_START_MARKER),
        existing.find(GENERATED_END_MARKER),
    ) {
        (Some(start), Some(end)) if start <= end => {
            let before = &existing[..start];
            let after = &existing[end + GENERATED_END_MARKER.len()..];
            format!("{before}{generated_block}{after}")
        }
        _ => {
            let trimmed = existing.trim_end();
            format!(
                "{trimmed}\n\n{GENERATED_SECTION_TITLE}\n\n{GENERATED_SECTION_NOTE}\n\n{generated_block}\n"
            )
        }
    }
}

fn resolve_workspace_root() -> Result<PathBuf, String> {
    let current_dir = std::env::current_dir().map_err(|err| format!("current_dir: {err}"))?;
    for candidate in current_dir.ancestors() {
        let cargo_toml = candidate.join("Cargo.toml");
        let Ok(text) = fs::read_to_string(&cargo_toml) else {
            continue;
        };
        if text.contains("[workspace]") {
            return Ok(candidate.to_path_buf());
        }
    }

    Err(format!(
        "could not resolve workspace root from {}",
        current_dir.display()
    ))
}

impl ManifestSupportState {
    fn as_str(self) -> &'static str {
        match self {
            Self::Supported => "supported",
            Self::Unsupported => "unsupported",
        }
    }
}

impl BackendSupportState {
    fn as_str(self) -> &'static str {
        match self {
            Self::Supported => "supported",
            Self::Partial => "partial",
            Self::Unsupported => "unsupported",
        }
    }
}

impl UaaSupportState {
    fn as_str(self) -> &'static str {
        match self {
            Self::Supported => "supported",
            Self::Partial => "partial",
            Self::Unsupported => "unsupported",
        }
    }
}

impl PointerPromotionState {
    fn as_str(self) -> &'static str {
        match self {
            Self::None => "none",
            Self::LatestSupported => "latest_supported",
            Self::LatestValidated => "latest_validated",
            Self::LatestSupportedAndValidated => "latest_supported_and_validated",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_rows() -> Vec<SupportRow> {
        vec![SupportRow {
            agent: "codex".to_string(),
            version: "1.0.0".to_string(),
            target: "linux-x64".to_string(),
            manifest_support: ManifestSupportState::Supported,
            backend_support: BackendSupportState::Partial,
            uaa_support: UaaSupportState::Partial,
            pointer_promotion: PointerPromotionState::LatestValidated,
            evidence_notes: vec![
                "backend report includes backend-only surface outside unified support"
                    .to_string(),
            ],
        }]
    }

    #[test]
    fn markdown_splice_preserves_normative_contract_text() {
        let existing = "# Spec\n\n## Purpose\nManual contract.\n";
        let projection = "### `codex`\n\n| agent | target | version | manifest_support | backend_support | uaa_support | pointer_promotion | evidence_notes |\n|---|---|---|---|---|---|---|---|\n";

        let updated = splice_markdown_projection(existing, projection);

        assert!(updated.contains("## Purpose\nManual contract."));
        assert!(updated.contains(GENERATED_SECTION_TITLE));
        assert!(updated.contains(GENERATED_START_MARKER));
        assert!(updated.contains("### `codex`"));
    }

    #[test]
    fn publication_bundle_uses_same_rows_for_json_and_markdown() {
        let rows = sample_rows();
        let bundle = render_publication_bundle(&rows).expect("render publication bundle");

        assert!(bundle.json.contains("\"schema_version\": 1"));
        assert!(bundle.json.contains("\"agent\": \"codex\""));
        assert!(bundle.markdown.contains("| `codex` | `linux-x64` | `1.0.0` |"));
        assert!(bundle.markdown.contains("backend report includes backend-only surface"));
    }
}
