use std::{fs, path::PathBuf};

use clap::Parser;
use serde::{Deserialize, Serialize};

#[path = "support_matrix/consistency.rs"]
mod consistency;
#[path = "support_matrix/derive.rs"]
mod derive;
#[path = "support_matrix/publication.rs"]
mod publication;

use publication::{
    render_publication_bundle, validate_publication_artifacts, write_publication_artifacts,
};

pub(crate) use consistency::{format_publication_issues, validate_publication_consistency};
pub(crate) use derive::derive_rows;
#[cfg(test)]
#[allow(unused_imports)]
pub(crate) use derive::derive_rows_for_test_roots;
#[allow(unused_imports)]
pub(crate) use publication::SupportMatrixArtifact;

const CURRENT_AGENT_ROOTS: [(&str, &str); 3] = [
    ("codex", "cli_manifests/codex"),
    ("claude_code", "cli_manifests/claude_code"),
    ("opencode", "cli_manifests/opencode"),
];
const JSON_OUTPUT_PATH: &str = "cli_manifests/support_matrix/current.json";
const MARKDOWN_OUTPUT_PATH: &str = "docs/specs/unified-agent-api/support-matrix.md";
const GENERATED_SECTION_TITLE: &str = "## Published support matrix";
const GENERATED_SECTION_NOTE: &str =
    "This section is generated by `cargo run -p xtask -- support-matrix`.\nDo not edit this section by hand.";
const GENERATED_START_MARKER: &str = "<!-- support-matrix-published:start -->";
const GENERATED_END_MARKER: &str = "<!-- support-matrix-published:end -->";

#[derive(Debug, Parser)]
pub struct Args {
    /// Verify the checked-in publication artifacts without rewriting them.
    #[arg(long)]
    pub check: bool,
}

pub fn run(args: Args) -> Result<(), String> {
    let workspace_root = resolve_workspace_root()?;
    let rows = derive_rows(&workspace_root)?;
    if let Err(issues) = validate_publication_consistency(&workspace_root, &rows) {
        return Err(format_publication_issues(&issues));
    }
    let bundle = render_publication_bundle(&rows)?;
    if args.check {
        validate_publication_artifacts(&workspace_root, &bundle)?;
    } else {
        write_publication_artifacts(&workspace_root, &bundle)?;
    }
    Ok(())
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SupportRow {
    pub agent: String,
    pub version: String,
    pub target: String,
    pub manifest_support: ManifestSupportState,
    pub backend_support: BackendSupportState,
    pub uaa_support: UaaSupportState,
    pub pointer_promotion: PointerPromotionState,
    #[serde(default)]
    pub evidence_notes: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ManifestSupportState {
    Supported,
    Unsupported,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BackendSupportState {
    Supported,
    Partial,
    Unsupported,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum UaaSupportState {
    Supported,
    Partial,
    Unsupported,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PointerPromotionState {
    None,
    LatestSupported,
    LatestValidated,
    LatestSupportedAndValidated,
}

fn resolve_workspace_root() -> Result<PathBuf, String> {
    let current_dir = std::env::current_dir().map_err(|err| format!("current_dir: {err}"))?;
    for candidate in current_dir.ancestors() {
        let cargo_toml = candidate.join("Cargo.toml");
        let Ok(text) = fs::read_to_string(&cargo_toml) else {
            continue;
        };
        if text.contains("[workspace]") {
            return Ok(candidate.to_path_buf());
        }
    }

    Err(format!(
        "could not resolve workspace root from {}",
        current_dir.display()
    ))
}

impl ManifestSupportState {
    fn as_str(self) -> &'static str {
        match self {
            Self::Supported => "supported",
            Self::Unsupported => "unsupported",
        }
    }
}

impl BackendSupportState {
    fn as_str(self) -> &'static str {
        match self {
            Self::Supported => "supported",
            Self::Partial => "partial",
            Self::Unsupported => "unsupported",
        }
    }
}

impl UaaSupportState {
    fn as_str(self) -> &'static str {
        match self {
            Self::Supported => "supported",
            Self::Partial => "partial",
            Self::Unsupported => "unsupported",
        }
    }
}

impl PointerPromotionState {
    fn as_str(self) -> &'static str {
        match self {
            Self::None => "none",
            Self::LatestSupported => "latest_supported",
            Self::LatestValidated => "latest_validated",
            Self::LatestSupportedAndValidated => "latest_supported_and_validated",
        }
    }
}
