use std::{
    cmp::Ordering,
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

use clap::Parser;
use semver::Version;
use serde::{Deserialize, Serialize};

use crate::wrapper_coverage_shared::RootIntakeLayout;

const CURRENT_AGENT_ROOTS: [(&str, &str); 2] = [
    ("codex", "cli_manifests/codex"),
    ("claude_code", "cli_manifests/claude_code"),
];
const JSON_OUTPUT_PATH: &str = "cli_manifests/support_matrix/current.json";
const MARKDOWN_OUTPUT_PATH: &str = "docs/specs/unified-agent-api/support-matrix.md";
const GENERATED_SECTION_TITLE: &str = "## Published support matrix";
const GENERATED_SECTION_NOTE: &str =
    "This section is generated by `cargo run -p xtask -- support-matrix`.\nDo not edit this section by hand.";
const GENERATED_START_MARKER: &str = "<!-- support-matrix-published:start -->";
const GENERATED_END_MARKER: &str = "<!-- support-matrix-published:end -->";

#[derive(Debug, Parser)]
pub struct Args {}

pub fn run(_args: Args) -> Result<(), String> {
    let workspace_root = resolve_workspace_root()?;
    let rows = derive_rows(&workspace_root)?;
    if let Err(issues) = validate_publication_consistency(&workspace_root, &rows) {
        return Err(format_publication_issues(&issues));
    }
    let bundle = render_publication_bundle(&rows)?;
    write_publication_artifacts(&workspace_root, &bundle)?;
    Ok(())
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SupportRow {
    pub agent: String,
    pub version: String,
    pub target: String,
    pub manifest_support: ManifestSupportState,
    pub backend_support: BackendSupportState,
    pub uaa_support: UaaSupportState,
    pub pointer_promotion: PointerPromotionState,
    #[serde(default)]
    pub evidence_notes: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ManifestSupportState {
    Supported,
    Unsupported,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BackendSupportState {
    Supported,
    Partial,
    Unsupported,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum UaaSupportState {
    Supported,
    Partial,
    Unsupported,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PointerPromotionState {
    None,
    LatestSupported,
    LatestValidated,
    LatestSupportedAndValidated,
}

#[derive(Debug, Clone)]
struct AgentRoot {
    agent: String,
    root: PathBuf,
}

#[derive(Debug, Deserialize)]
struct CurrentUnion {
    #[serde(default)]
    expected_targets: Vec<String>,
    #[serde(default)]
    inputs: Vec<CurrentUnionInput>,
}

#[derive(Debug, Deserialize)]
struct CurrentUnionInput {
    target_triple: String,
    #[serde(default)]
    binary: CurrentUnionBinary,
}

#[derive(Debug, Default, Deserialize)]
struct CurrentUnionBinary {
    semantic_version: Option<String>,
}

#[derive(Debug, Deserialize)]
struct VersionMetadata {
    semantic_version: String,
    #[serde(default)]
    status: Option<String>,
    coverage: VersionCoverage,
}

#[derive(Debug, Deserialize)]
struct VersionCoverage {
    #[serde(default)]
    supported_targets: Vec<String>,
}

#[derive(Debug, Default, Deserialize)]
struct SupportReport {
    #[serde(default)]
    inputs: SupportReportInputs,
    #[serde(default)]
    deltas: SupportReportDeltas,
}

#[derive(Debug, Default, Deserialize)]
struct SupportReportInputs {
    #[serde(default)]
    upstream: SupportReportUpstream,
}

#[derive(Debug, Default, Deserialize)]
struct SupportReportUpstream {
    #[serde(default)]
    targets: Vec<String>,
}

#[derive(Debug, Default, Deserialize)]
struct SupportReportDeltas {
    #[serde(default)]
    missing_commands: Vec<serde_json::Value>,
    #[serde(default)]
    missing_flags: Vec<serde_json::Value>,
    #[serde(default)]
    missing_args: Vec<serde_json::Value>,
    #[serde(default)]
    intentionally_unsupported: Vec<serde_json::Value>,
    #[serde(default)]
    wrapper_only_commands: Vec<serde_json::Value>,
    #[serde(default)]
    wrapper_only_flags: Vec<serde_json::Value>,
    #[serde(default)]
    wrapper_only_args: Vec<serde_json::Value>,
}

#[derive(Debug, Clone)]
struct CurrentRootPosture {
    expected_targets: Vec<String>,
    current_version: Option<String>,
    current_targets: BTreeSet<String>,
}

#[derive(Debug, Clone)]
struct PointerSet {
    latest_supported: BTreeMap<String, Option<String>>,
    latest_validated: BTreeMap<String, Option<String>>,
}

#[derive(Debug, Clone)]
struct PublicationBundle {
    json: String,
    markdown: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct SupportMatrixArtifact {
    pub(crate) schema_version: u8,
    pub(crate) rows: Vec<SupportRow>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct SupportMatrixConsistencyIssue {
    pub code: &'static str,
    pub agent: String,
    pub version: String,
    pub target: String,
    pub message: String,
}

impl SupportMatrixConsistencyIssue {
    fn pointer_promotion_mismatch(row: &SupportRow, observed: PointerPromotionState) -> Self {
        Self {
            code: "SUPPORT_MATRIX_POINTER_PROMOTION_MISMATCH",
            agent: row.agent.clone(),
            version: row.version.clone(),
            target: row.target.clone(),
            message: format!(
                "row pointer_promotion={} does not match committed pointer state {}",
                row.pointer_promotion.as_str(),
                observed.as_str()
            ),
        }
    }

    fn omission_contradiction(row: &SupportRow, expected_notes: &[String]) -> Self {
        Self {
            code: "SUPPORT_MATRIX_CURRENT_SNAPSHOT_OMISSION_MISMATCH",
            agent: row.agent.clone(),
            version: row.version.clone(),
            target: row.target.clone(),
            message: format!(
                "row claims support truth incompatible with current snapshot omission evidence; expected notes {:?}",
                expected_notes
            ),
        }
    }

    fn evidence_notes_mismatch(row: &SupportRow, expected_notes: &[String]) -> Self {
        Self {
            code: "SUPPORT_MATRIX_EVIDENCE_NOTES_MISMATCH",
            agent: row.agent.clone(),
            version: row.version.clone(),
            target: row.target.clone(),
            message: format!(
                "row evidence_notes {:?} do not match committed evidence {:?}",
                row.evidence_notes, expected_notes
            ),
        }
    }
}

pub(crate) fn derive_rows(workspace_root: &Path) -> Result<Vec<SupportRow>, String> {
    let roots = CURRENT_AGENT_ROOTS
        .iter()
        .map(|(agent, rel_root)| AgentRoot {
            agent: (*agent).to_string(),
            root: workspace_root.join(rel_root),
        })
        .collect::<Vec<_>>();
    derive_rows_for_roots(&roots)
}

pub(crate) fn validate_publication_consistency(
    workspace_root: &Path,
    rows: &[SupportRow],
) -> Result<(), Vec<SupportMatrixConsistencyIssue>> {
    let mut issues = Vec::new();
    let mut roots = BTreeMap::new();

    let required_agents = rows
        .iter()
        .map(|row| row.agent.as_str())
        .collect::<BTreeSet<_>>();
    if required_agents.is_empty() {
        return Ok(());
    }

    for agent in required_agents {
        let Some((_, rel_root)) = CURRENT_AGENT_ROOTS
            .iter()
            .find(|(candidate, _)| *candidate == agent)
        else {
            issues.push(SupportMatrixConsistencyIssue {
                code: "SUPPORT_MATRIX_UNKNOWN_AGENT",
                agent: agent.to_string(),
                version: String::new(),
                target: String::new(),
                message: "row agent does not match a committed manifest root".to_string(),
            });
            continue;
        };
        let root = AgentRoot {
            agent: agent.to_string(),
            root: workspace_root.join(rel_root),
        };
        let posture = match read_current_root_posture(&root.root) {
            Ok(posture) => posture,
            Err(err) => {
                issues.push(SupportMatrixConsistencyIssue {
                    code: "SUPPORT_MATRIX_ROOT_READ_ERROR",
                    agent: root.agent.clone(),
                    version: String::new(),
                    target: String::new(),
                    message: err,
                });
                continue;
            }
        };
        let pointers = match read_pointers(&root.root, &posture.expected_targets) {
            Ok(pointers) => pointers,
            Err(err) => {
                issues.push(SupportMatrixConsistencyIssue {
                    code: "SUPPORT_MATRIX_POINTER_READ_ERROR",
                    agent: root.agent.clone(),
                    version: String::new(),
                    target: String::new(),
                    message: err,
                });
                continue;
            }
        };
        roots.insert(
            root.agent.clone(),
            RootConsistencyContext {
                posture,
                pointers,
                layout: RootIntakeLayout::new(root.root.clone()),
                version_statuses: match read_version_statuses(&root.root) {
                    Ok(version_statuses) => version_statuses,
                    Err(err) => {
                        issues.push(SupportMatrixConsistencyIssue {
                            code: "SUPPORT_MATRIX_VERSION_STATUS_READ_ERROR",
                            agent: root.agent.clone(),
                            version: String::new(),
                            target: String::new(),
                            message: err,
                        });
                        continue;
                    }
                },
            },
        );
    }

    for row in rows {
        let Some(ctx) = roots.get(&row.agent) else {
            continue;
        };

        validate_row_consistency(row, ctx, &mut issues);
    }

    if issues.is_empty() {
        Ok(())
    } else {
        Err(issues)
    }
}

fn derive_rows_for_roots(roots: &[AgentRoot]) -> Result<Vec<SupportRow>, String> {
    let mut rows = Vec::new();
    for root in roots {
        rows.extend(derive_rows_for_root(root)?);
    }

    rows.sort_by(|left, right| compare_rows(left, right));
    Ok(rows)
}

fn derive_rows_for_root(root: &AgentRoot) -> Result<Vec<SupportRow>, String> {
    let posture = read_current_root_posture(&root.root)?;
    let pointers = read_pointers(&root.root, &posture.expected_targets)?;
    let layout = RootIntakeLayout::new(root.root.clone());

    let mut rows = Vec::new();
    let versions_dir = layout.versions_dir();
    for entry in fs::read_dir(&versions_dir)
        .map_err(|err| format!("read_dir({}): {err}", versions_dir.display()))?
    {
        let entry = entry.map_err(|err| format!("read_dir entry error: {err}"))?;
        let path = entry.path();
        if path.extension().and_then(|ext| ext.to_str()) != Some("json") {
            continue;
        }

        let metadata: VersionMetadata = read_json(&path)?;
        let supported_targets = metadata
            .coverage
            .supported_targets
            .into_iter()
            .collect::<BTreeSet<_>>();

        for target in posture.expected_targets.iter() {
            let manifest_support = if supported_targets.contains(target) {
                ManifestSupportState::Supported
            } else {
                ManifestSupportState::Unsupported
            };

            let report = load_support_report(&layout, &metadata.semantic_version, target)?;
            let backend_support = classify_backend_support(report.as_ref());
            let pointer_promotion =
                classify_pointer_promotion(&pointers, target, &metadata.semantic_version);
            let evidence_notes = build_evidence_notes(
                report.as_ref(),
                &posture,
                target,
                &metadata.semantic_version,
            );
            let uaa_support =
                classify_uaa_support(manifest_support, backend_support, &evidence_notes);

            rows.push(SupportRow {
                agent: root.agent.clone(),
                version: metadata.semantic_version.clone(),
                target: target.clone(),
                manifest_support,
                backend_support,
                uaa_support,
                pointer_promotion,
                evidence_notes,
            });
        }
    }

    Ok(rows)
}

fn format_publication_issues(issues: &[SupportMatrixConsistencyIssue]) -> String {
    let mut out = String::from("support-matrix publication contradictions detected");
    for issue in issues {
        out.push_str(&format!(
            "\n- [{}] {} {} {}: {}",
            issue.code, issue.agent, issue.version, issue.target, issue.message
        ));
    }
    out
}

fn read_version_statuses(root: &Path) -> Result<BTreeMap<String, Option<String>>, String> {
    let layout = RootIntakeLayout::new(root.to_path_buf());
    let versions_dir = layout.versions_dir();
    let mut version_statuses = BTreeMap::new();

    for entry in fs::read_dir(&versions_dir)
        .map_err(|err| format!("read_dir({}): {err}", versions_dir.display()))?
    {
        let entry = entry.map_err(|err| format!("read_dir entry error: {err}"))?;
        let path = entry.path();
        if path.extension().and_then(|ext| ext.to_str()) != Some("json") {
            continue;
        }

        let metadata: VersionMetadata = read_json(&path)?;
        version_statuses.insert(metadata.semantic_version, metadata.status);
    }

    Ok(version_statuses)
}

#[derive(Debug, Clone)]
struct RootConsistencyContext {
    posture: CurrentRootPosture,
    pointers: PointerSet,
    layout: RootIntakeLayout,
    version_statuses: BTreeMap<String, Option<String>>,
}

fn read_current_root_posture(root: &Path) -> Result<CurrentRootPosture, String> {
    let current_path = root.join("current.json");
    let current: CurrentUnion = read_json(&current_path)?;
    if current.expected_targets.is_empty() {
        return Err(format!(
            "{}: expected_targets must not be empty",
            current_path.display()
        ));
    }

    let mut versions = BTreeSet::new();
    let current_targets = current
        .inputs
        .iter()
        .map(|input| {
            if let Some(version) = input.binary.semantic_version.clone() {
                versions.insert(version);
            }
            input.target_triple.clone()
        })
        .collect::<BTreeSet<_>>();

    let current_version = match versions.len() {
        0 => None,
        1 => versions.into_iter().next(),
        _ => {
            return Err(format!(
                "{}: current.json contained multiple semantic versions",
                current_path.display()
            ));
        }
    };

    Ok(CurrentRootPosture {
        expected_targets: current.expected_targets,
        current_version,
        current_targets,
    })
}

fn read_pointers(root: &Path, expected_targets: &[String]) -> Result<PointerSet, String> {
    let layout = RootIntakeLayout::new(root.to_path_buf());
    let mut latest_supported = BTreeMap::new();
    let mut latest_validated = BTreeMap::new();

    for target in expected_targets {
        latest_supported.insert(
            target.clone(),
            read_pointer_file(&layout.latest_supported_pointer_path(target))?,
        );
        latest_validated.insert(
            target.clone(),
            read_pointer_file(&layout.latest_validated_pointer_path(target))?,
        );
    }

    Ok(PointerSet {
        latest_supported,
        latest_validated,
    })
}

fn read_pointer_file(path: &Path) -> Result<Option<String>, String> {
    let raw = fs::read_to_string(path).map_err(|err| format!("read({}): {err}", path.display()))?;
    let value = raw.trim();
    if value.is_empty() || value == "none" {
        Ok(None)
    } else {
        Ok(Some(value.to_string()))
    }
}

fn load_support_report(
    layout: &RootIntakeLayout,
    version: &str,
    target: &str,
) -> Result<Option<SupportReport>, String> {
    let version_dir = layout.reports_version_dir(version);
    let exact_target = version_dir.join(format!("coverage.{target}.json"));
    if exact_target.exists() {
        return read_json(&exact_target).map(Some);
    }

    for candidate in [
        version_dir.join("coverage.any.json"),
        version_dir.join("coverage.all.json"),
    ] {
        if !candidate.exists() {
            continue;
        }

        let report: SupportReport = read_json(&candidate)?;
        if report_mentions_target(&report, target) {
            return Ok(Some(report));
        }
    }
    Ok(None)
}

fn report_mentions_target(report: &SupportReport, target: &str) -> bool {
    report.inputs.upstream.targets.is_empty()
        || report
            .inputs
            .upstream
            .targets
            .iter()
            .any(|candidate| candidate == target)
}

fn classify_backend_support(report: Option<&SupportReport>) -> BackendSupportState {
    let Some(report) = report else {
        return BackendSupportState::Unsupported;
    };

    if report_has_missing_surface(report) {
        return BackendSupportState::Unsupported;
    }

    if report_has_partial_caveat(report) {
        return BackendSupportState::Partial;
    }

    BackendSupportState::Supported
}

fn report_has_missing_surface(report: &SupportReport) -> bool {
    !report.deltas.missing_commands.is_empty()
        || !report.deltas.missing_flags.is_empty()
        || !report.deltas.missing_args.is_empty()
}

fn report_has_partial_caveat(report: &SupportReport) -> bool {
    !report.deltas.intentionally_unsupported.is_empty()
        || !report.deltas.wrapper_only_commands.is_empty()
        || !report.deltas.wrapper_only_flags.is_empty()
        || !report.deltas.wrapper_only_args.is_empty()
}

fn classify_pointer_promotion(
    pointers: &PointerSet,
    target: &str,
    version: &str,
) -> PointerPromotionState {
    let latest_supported = pointers
        .latest_supported
        .get(target)
        .and_then(|value| value.as_deref())
        == Some(version);
    let latest_validated = pointers
        .latest_validated
        .get(target)
        .and_then(|value| value.as_deref())
        == Some(version);

    match (latest_supported, latest_validated) {
        (true, true) => PointerPromotionState::LatestSupportedAndValidated,
        (true, false) => PointerPromotionState::LatestSupported,
        (false, true) => PointerPromotionState::LatestValidated,
        (false, false) => PointerPromotionState::None,
    }
}

fn build_evidence_notes(
    report: Option<&SupportReport>,
    posture: &CurrentRootPosture,
    target: &str,
    version: &str,
) -> Vec<String> {
    let mut notes = Vec::new();

    if let Some(report) = report {
        if !report.deltas.intentionally_unsupported.is_empty() {
            notes.push(
                "backend report includes intentionally unsupported surface outside unified support"
                    .to_string(),
            );
        }
        if !report.deltas.wrapper_only_commands.is_empty()
            || !report.deltas.wrapper_only_flags.is_empty()
            || !report.deltas.wrapper_only_args.is_empty()
        {
            notes.push(
                "backend report includes backend-only surface outside unified support".to_string(),
            );
        }
    }

    if posture.current_version.as_deref() == Some(version)
        && !posture.current_targets.contains(target)
    {
        notes.push("current root snapshot omits this target".to_string());
    }

    notes
}

fn validate_row_consistency(
    row: &SupportRow,
    ctx: &RootConsistencyContext,
    issues: &mut Vec<SupportMatrixConsistencyIssue>,
) {
    let observed_promotion = classify_pointer_promotion(&ctx.pointers, &row.target, &row.version);
    if row.pointer_promotion != observed_promotion {
        issues.push(SupportMatrixConsistencyIssue::pointer_promotion_mismatch(
            row,
            observed_promotion,
        ));
    }

    let report = match load_support_report(&ctx.layout, &row.version, &row.target) {
        Ok(report) => report,
        Err(err) => {
            issues.push(SupportMatrixConsistencyIssue {
                code: "SUPPORT_MATRIX_REPORT_READ_ERROR",
                agent: row.agent.clone(),
                version: row.version.clone(),
                target: row.target.clone(),
                message: err,
            });
            return;
        }
    };
    let expected_notes =
        build_evidence_notes(report.as_ref(), &ctx.posture, &row.target, &row.version);

    if expected_notes != row.evidence_notes {
        issues.push(SupportMatrixConsistencyIssue::evidence_notes_mismatch(
            row,
            &expected_notes,
        ));
    }

    if let Some(status) = ctx
        .version_statuses
        .get(&row.version)
        .and_then(|value| value.as_deref())
    {
        let requires_validation_status = matches!(
            row.pointer_promotion,
            PointerPromotionState::LatestValidated
                | PointerPromotionState::LatestSupportedAndValidated
        );
        if requires_validation_status && !matches!(status, "validated" | "supported") {
            issues.push(SupportMatrixConsistencyIssue {
                code: "SUPPORT_MATRIX_VERSION_STATUS_MISMATCH",
                agent: row.agent.clone(),
                version: row.version.clone(),
                target: row.target.clone(),
                message: format!(
                    "row pointer_promotion={} requires version status validated or supported, got {}",
                    row.pointer_promotion.as_str(),
                    status
                ),
            });
        }
    }

    let omitted_current_target = ctx.posture.current_version.as_deref()
        == Some(row.version.as_str())
        && !ctx.posture.current_targets.contains(&row.target);
    if omitted_current_target {
        let support_is_unsupported = row.manifest_support == ManifestSupportState::Unsupported
            && row.backend_support == BackendSupportState::Unsupported
            && row.uaa_support == UaaSupportState::Unsupported
            && row.pointer_promotion == PointerPromotionState::None;
        if !support_is_unsupported {
            issues.push(SupportMatrixConsistencyIssue::omission_contradiction(
                row,
                &expected_notes,
            ));
        }
    }
}

fn classify_uaa_support(
    manifest_support: ManifestSupportState,
    backend_support: BackendSupportState,
    evidence_notes: &[String],
) -> UaaSupportState {
    match (manifest_support, backend_support) {
        (ManifestSupportState::Supported, BackendSupportState::Supported)
            if evidence_notes.is_empty() =>
        {
            UaaSupportState::Supported
        }
        (ManifestSupportState::Supported, BackendSupportState::Unsupported)
        | (ManifestSupportState::Unsupported, BackendSupportState::Supported)
        | (ManifestSupportState::Unsupported, BackendSupportState::Unsupported) => {
            UaaSupportState::Unsupported
        }
        _ => UaaSupportState::Partial,
    }
}

fn compare_rows(left: &SupportRow, right: &SupportRow) -> Ordering {
    left.agent
        .cmp(&right.agent)
        .then_with(|| left.target.cmp(&right.target))
        .then_with(|| compare_semver_desc(&left.version, &right.version))
}

fn compare_semver_desc(left: &str, right: &str) -> Ordering {
    match (Version::parse(left), Version::parse(right)) {
        (Ok(left), Ok(right)) => right.cmp(&left),
        _ => right.cmp(left),
    }
}

fn read_json<T>(path: &Path) -> Result<T, String>
where
    T: for<'de> Deserialize<'de>,
{
    let text =
        fs::read_to_string(path).map_err(|err| format!("read({}): {err}", path.display()))?;
    serde_json::from_str(&text).map_err(|err| format!("parse({}): {err}", path.display()))
}

fn render_publication_bundle(rows: &[SupportRow]) -> Result<PublicationBundle, String> {
    let json = serde_json::to_string_pretty(&SupportMatrixArtifact {
        schema_version: 1,
        rows: rows.to_vec(),
    })
    .map_err(|err| format!("serialize support-matrix json: {err}"))?;
    let markdown = render_markdown_projection(rows);

    Ok(PublicationBundle {
        json: format!("{json}\n"),
        markdown,
    })
}

fn render_markdown_projection(rows: &[SupportRow]) -> String {
    let mut out = String::new();
    let mut current_agent: Option<&str> = None;

    for row in rows {
        if current_agent != Some(row.agent.as_str()) {
            if current_agent.is_some() {
                out.push('\n');
            }
            current_agent = Some(row.agent.as_str());
            out.push_str(&format!("### `{}`\n\n", row.agent));
            out.push_str("| agent | target | version | manifest_support | backend_support | uaa_support | pointer_promotion | evidence_notes |\n");
            out.push_str("|---|---|---|---|---|---|---|---|\n");
        }

        let notes = if row.evidence_notes.is_empty() {
            "—".to_string()
        } else {
            row.evidence_notes.join("; ")
        };

        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | `{}` | `{}` | `{}` | `{}` | {} |\n",
            row.agent,
            row.target,
            row.version,
            row.manifest_support.as_str(),
            row.backend_support.as_str(),
            row.uaa_support.as_str(),
            row.pointer_promotion.as_str(),
            notes
        ));
    }

    out
}

fn write_publication_artifacts(
    workspace_root: &Path,
    bundle: &PublicationBundle,
) -> Result<(), String> {
    let json_path = workspace_root.join(JSON_OUTPUT_PATH);
    let markdown_path = workspace_root.join(MARKDOWN_OUTPUT_PATH);
    write_file(&json_path, &bundle.json)?;

    let existing_markdown = fs::read_to_string(&markdown_path)
        .map_err(|err| format!("read({}): {err}", markdown_path.display()))?;
    let updated_markdown = splice_markdown_projection(&existing_markdown, &bundle.markdown);
    write_file(&markdown_path, &updated_markdown)?;
    Ok(())
}

fn write_file(path: &Path, contents: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|err| format!("create_dir_all({}): {err}", parent.display()))?;
    }
    fs::write(path, contents).map_err(|err| format!("write({}): {err}", path.display()))
}

fn splice_markdown_projection(existing: &str, projection: &str) -> String {
    let generated_block = format!("{GENERATED_START_MARKER}\n{projection}{GENERATED_END_MARKER}");

    match (
        existing.find(GENERATED_START_MARKER),
        existing.find(GENERATED_END_MARKER),
    ) {
        (Some(start), Some(end)) if start <= end => {
            let before = &existing[..start];
            let after = &existing[end + GENERATED_END_MARKER.len()..];
            format!("{before}{generated_block}{after}")
        }
        _ => {
            let trimmed = existing.trim_end();
            format!(
                "{trimmed}\n\n{GENERATED_SECTION_TITLE}\n\n{GENERATED_SECTION_NOTE}\n\n{generated_block}\n"
            )
        }
    }
}

fn resolve_workspace_root() -> Result<PathBuf, String> {
    let current_dir = std::env::current_dir().map_err(|err| format!("current_dir: {err}"))?;
    for candidate in current_dir.ancestors() {
        let cargo_toml = candidate.join("Cargo.toml");
        let Ok(text) = fs::read_to_string(&cargo_toml) else {
            continue;
        };
        if text.contains("[workspace]") {
            return Ok(candidate.to_path_buf());
        }
    }

    Err(format!(
        "could not resolve workspace root from {}",
        current_dir.display()
    ))
}

impl ManifestSupportState {
    fn as_str(self) -> &'static str {
        match self {
            Self::Supported => "supported",
            Self::Unsupported => "unsupported",
        }
    }
}

impl BackendSupportState {
    fn as_str(self) -> &'static str {
        match self {
            Self::Supported => "supported",
            Self::Partial => "partial",
            Self::Unsupported => "unsupported",
        }
    }
}

impl UaaSupportState {
    fn as_str(self) -> &'static str {
        match self {
            Self::Supported => "supported",
            Self::Partial => "partial",
            Self::Unsupported => "unsupported",
        }
    }
}

impl PointerPromotionState {
    fn as_str(self) -> &'static str {
        match self {
            Self::None => "none",
            Self::LatestSupported => "latest_supported",
            Self::LatestValidated => "latest_validated",
            Self::LatestSupportedAndValidated => "latest_supported_and_validated",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn make_temp_dir(prefix: &str) -> PathBuf {
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time after unix epoch");
        let dir = std::env::temp_dir().join(format!(
            "{prefix}-{}-{}",
            std::process::id(),
            now.as_nanos()
        ));
        fs::create_dir_all(&dir).expect("create temp dir");
        dir
    }

    fn write_text(path: &Path, contents: &str) {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).expect("create parent dirs");
        }
        fs::write(path, contents).expect("write file");
    }

    fn write_json(path: &Path, value: &serde_json::Value) {
        let text = serde_json::to_string_pretty(value).expect("serialize json");
        write_text(path, &format!("{text}\n"));
    }

    fn materialize_root(
        root: &Path,
        expected_targets: &[&str],
        current_version: &str,
        current_targets: &[&str],
        versions: &[(&str, &[&str])],
        pointers_supported: &[(&str, &str)],
        pointers_validated: &[(&str, &str)],
        reports: &[(&str, &str, serde_json::Value)],
    ) {
        let inputs = current_targets
            .iter()
            .map(|target| {
                json!({
                    "target_triple": target,
                    "binary": { "semantic_version": current_version },
                })
            })
            .collect::<Vec<_>>();

        write_json(
            &root.join("current.json"),
            &json!({
                "expected_targets": expected_targets,
                "inputs": inputs,
            }),
        );

        for (version, supported_targets) in versions {
            write_json(
                &root.join("versions").join(format!("{version}.json")),
                &json!({
                    "semantic_version": version,
                    "coverage": {
                        "supported_targets": supported_targets,
                    },
                }),
            );
        }

        for target in expected_targets {
            let latest_supported = pointers_supported
                .iter()
                .find_map(|(candidate, version)| (*candidate == *target).then_some(*version))
                .unwrap_or("none");
            let latest_validated = pointers_validated
                .iter()
                .find_map(|(candidate, version)| (*candidate == *target).then_some(*version))
                .unwrap_or("none");
            write_text(
                &root
                    .join("pointers/latest_supported")
                    .join(format!("{target}.txt")),
                &format!("{latest_supported}\n"),
            );
            write_text(
                &root
                    .join("pointers/latest_validated")
                    .join(format!("{target}.txt")),
                &format!("{latest_validated}\n"),
            );
        }

        for (version, report_name, report) in reports {
            write_json(
                &root.join("reports").join(version).join(report_name),
                report,
            );
        }
    }

    fn sample_rows() -> Vec<SupportRow> {
        vec![SupportRow {
            agent: "codex".to_string(),
            version: "1.0.0".to_string(),
            target: "linux-x64".to_string(),
            manifest_support: ManifestSupportState::Supported,
            backend_support: BackendSupportState::Partial,
            uaa_support: UaaSupportState::Partial,
            pointer_promotion: PointerPromotionState::LatestValidated,
            evidence_notes: vec![
                "backend report includes backend-only surface outside unified support".to_string(),
            ],
        }]
    }

    #[test]
    fn markdown_splice_preserves_normative_contract_text() {
        let existing = "# Spec\n\n## Purpose\nManual contract.\n";
        let projection = "### `codex`\n\n| agent | target | version | manifest_support | backend_support | uaa_support | pointer_promotion | evidence_notes |\n|---|---|---|---|---|---|---|---|\n";

        let updated = splice_markdown_projection(existing, projection);

        assert!(updated.contains("## Purpose\nManual contract."));
        assert!(updated.contains(GENERATED_SECTION_TITLE));
        assert!(updated.contains(GENERATED_START_MARKER));
        assert!(updated.contains("### `codex`"));
    }

    #[test]
    fn publication_bundle_uses_same_rows_for_json_and_markdown() {
        let rows = sample_rows();
        let bundle = render_publication_bundle(&rows).expect("render publication bundle");

        assert!(bundle.json.contains("\"schema_version\": 1"));
        assert!(bundle.json.contains("\"agent\": \"codex\""));
        assert!(bundle
            .markdown
            .contains("| `codex` | `linux-x64` | `1.0.0` |"));
        assert!(bundle
            .markdown
            .contains("backend report includes backend-only surface"));
    }

    #[test]
    fn publication_consistency_passes_for_matching_rows() {
        let workspace = make_temp_dir("support-matrix-consistency-pass");

        materialize_root(
            &workspace.join("cli_manifests/codex"),
            &["linux-x64", "win32-x64"],
            "1.0.0",
            &["linux-x64"],
            &[("0.9.0", &["linux-x64"]), ("1.0.0", &["linux-x64"])],
            &[("linux-x64", "0.9.0")],
            &[("linux-x64", "1.0.0")],
            &[(
                "1.0.0",
                "coverage.linux-x64.json",
                serde_json::json!({
                    "deltas": {
                        "missing_commands": [],
                        "missing_flags": [],
                        "missing_args": [],
                        "intentionally_unsupported": [],
                        "wrapper_only_commands": [
                            { "path": ["backend-only"] }
                        ],
                        "wrapper_only_flags": [],
                        "wrapper_only_args": [],
                    }
                }),
            )],
        );

        materialize_root(
            &workspace.join("cli_manifests/claude_code"),
            &["linux-x64"],
            "2.0.0",
            &["linux-x64"],
            &[("2.0.0", &["linux-x64"])],
            &[("linux-x64", "2.0.0")],
            &[("linux-x64", "2.0.0")],
            &[(
                "2.0.0",
                "coverage.linux-x64.json",
                serde_json::json!({
                    "deltas": {
                        "missing_commands": [],
                        "missing_flags": [],
                        "missing_args": [],
                        "intentionally_unsupported": [],
                        "wrapper_only_commands": [],
                        "wrapper_only_flags": [],
                        "wrapper_only_args": [],
                    }
                }),
            )],
        );

        let rows = derive_rows(&workspace).expect("derive rows");
        validate_publication_consistency(&workspace, &rows).expect("matching rows should pass");
    }

    #[test]
    fn publication_consistency_rejects_pointer_promotion_drift() {
        let workspace = make_temp_dir("support-matrix-consistency-pointer");

        materialize_root(
            &workspace.join("cli_manifests/codex"),
            &["linux-x64"],
            "1.0.0",
            &["linux-x64"],
            &[("1.0.0", &["linux-x64"])],
            &[("linux-x64", "1.0.0")],
            &[("linux-x64", "1.0.0")],
            &[(
                "1.0.0",
                "coverage.linux-x64.json",
                serde_json::json!({
                    "deltas": {
                        "missing_commands": [],
                        "missing_flags": [],
                        "missing_args": [],
                        "intentionally_unsupported": [],
                        "wrapper_only_commands": [],
                        "wrapper_only_flags": [],
                        "wrapper_only_args": [],
                    }
                }),
            )],
        );

        materialize_root(
            &workspace.join("cli_manifests/claude_code"),
            &["linux-x64"],
            "2.0.0",
            &["linux-x64"],
            &[("2.0.0", &["linux-x64"])],
            &[("linux-x64", "2.0.0")],
            &[("linux-x64", "2.0.0")],
            &[(
                "2.0.0",
                "coverage.linux-x64.json",
                serde_json::json!({
                    "deltas": {
                        "missing_commands": [],
                        "missing_flags": [],
                        "missing_args": [],
                        "intentionally_unsupported": [],
                        "wrapper_only_commands": [],
                        "wrapper_only_flags": [],
                        "wrapper_only_args": [],
                    }
                }),
            )],
        );

        let mut rows = derive_rows(&workspace).expect("derive rows");
        let row = rows
            .iter_mut()
            .find(|row| row.agent == "codex" && row.version == "1.0.0" && row.target == "linux-x64")
            .expect("expected codex row");
        row.pointer_promotion = PointerPromotionState::None;

        let issues = validate_publication_consistency(&workspace, &rows)
            .expect_err("pointer drift should be rejected");
        assert!(
            issues
                .iter()
                .any(|issue| issue.code == "SUPPORT_MATRIX_POINTER_PROMOTION_MISMATCH"),
            "expected pointer promotion mismatch, got: {issues:#?}"
        );
    }

    #[test]
    fn publication_consistency_rejects_omission_claim_and_note_drift() {
        let workspace = make_temp_dir("support-matrix-consistency-omission");

        materialize_root(
            &workspace.join("cli_manifests/codex"),
            &["linux-x64", "win32-x64"],
            "1.0.0",
            &["linux-x64"],
            &[("1.0.0", &["linux-x64"])],
            &[("linux-x64", "1.0.0")],
            &[("linux-x64", "1.0.0")],
            &[(
                "1.0.0",
                "coverage.linux-x64.json",
                serde_json::json!({
                    "deltas": {
                        "missing_commands": [],
                        "missing_flags": [],
                        "missing_args": [],
                        "intentionally_unsupported": [],
                        "wrapper_only_commands": [],
                        "wrapper_only_flags": [],
                        "wrapper_only_args": [],
                    }
                }),
            )],
        );

        materialize_root(
            &workspace.join("cli_manifests/claude_code"),
            &["linux-x64"],
            "2.0.0",
            &["linux-x64"],
            &[("2.0.0", &["linux-x64"])],
            &[("linux-x64", "2.0.0")],
            &[("linux-x64", "2.0.0")],
            &[(
                "2.0.0",
                "coverage.linux-x64.json",
                serde_json::json!({
                    "deltas": {
                        "missing_commands": [],
                        "missing_flags": [],
                        "missing_args": [],
                        "intentionally_unsupported": [],
                        "wrapper_only_commands": [],
                        "wrapper_only_flags": [],
                        "wrapper_only_args": [],
                    }
                }),
            )],
        );

        let mut rows = derive_rows(&workspace).expect("derive rows");
        let row = rows
            .iter_mut()
            .find(|row| row.agent == "codex" && row.version == "1.0.0" && row.target == "win32-x64")
            .expect("expected omitted codex row");
        row.manifest_support = ManifestSupportState::Supported;
        row.backend_support = BackendSupportState::Supported;
        row.uaa_support = UaaSupportState::Supported;
        row.pointer_promotion = PointerPromotionState::LatestValidated;
        row.evidence_notes.clear();

        let issues = validate_publication_consistency(&workspace, &rows)
            .expect_err("omission contradiction should be rejected");
        assert!(
            issues
                .iter()
                .any(|issue| issue.code == "SUPPORT_MATRIX_CURRENT_SNAPSHOT_OMISSION_MISMATCH"),
            "expected omission mismatch, got: {issues:#?}"
        );
        assert!(
            issues
                .iter()
                .any(|issue| issue.code == "SUPPORT_MATRIX_EVIDENCE_NOTES_MISMATCH"),
            "expected note mismatch, got: {issues:#?}"
        );
    }

    #[test]
    fn publication_consistency_rejects_status_drift_for_latest_validated_rows() {
        let workspace = make_temp_dir("support-matrix-consistency-status");

        materialize_root(
            &workspace.join("cli_manifests/codex"),
            &["linux-x64"],
            "1.0.0",
            &["linux-x64"],
            &[("1.0.0", &["linux-x64"])],
            &[("linux-x64", "1.0.0")],
            &[("linux-x64", "1.0.0")],
            &[(
                "1.0.0",
                "coverage.linux-x64.json",
                serde_json::json!({
                    "deltas": {
                        "missing_commands": [],
                        "missing_flags": [],
                        "missing_args": [],
                        "intentionally_unsupported": [],
                        "wrapper_only_commands": [],
                        "wrapper_only_flags": [],
                        "wrapper_only_args": [],
                    }
                }),
            )],
        );
        write_json(
            &workspace.join("cli_manifests/codex/versions/1.0.0.json"),
            &json!({
                "semantic_version": "1.0.0",
                "status": "reported",
                "coverage": {
                    "supported_targets": ["linux-x64"],
                },
            }),
        );

        materialize_root(
            &workspace.join("cli_manifests/claude_code"),
            &["linux-x64"],
            "2.0.0",
            &["linux-x64"],
            &[("2.0.0", &["linux-x64"])],
            &[("linux-x64", "2.0.0")],
            &[("linux-x64", "2.0.0")],
            &[(
                "2.0.0",
                "coverage.linux-x64.json",
                serde_json::json!({
                    "deltas": {
                        "missing_commands": [],
                        "missing_flags": [],
                        "missing_args": [],
                        "intentionally_unsupported": [],
                        "wrapper_only_commands": [],
                        "wrapper_only_flags": [],
                        "wrapper_only_args": [],
                    }
                }),
            )],
        );

        let rows = derive_rows(&workspace).expect("derive rows");
        let issues = validate_publication_consistency(&workspace, &rows)
            .expect_err("reported status should not allow latest_validated promotion");
        assert!(
            issues
                .iter()
                .any(|issue| issue.code == "SUPPORT_MATRIX_VERSION_STATUS_MISMATCH"),
            "expected status mismatch, got: {issues:#?}"
        );
    }
}
