#![allow(dead_code, unused_imports)]

use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
};

#[path = "support/onboard_agent_harness.rs"]
mod harness;

#[path = "../src/agent_registry.rs"]
mod agent_registry;
#[path = "../src/approval_artifact.rs"]
mod approval_artifact;
#[path = "../src/agent_maintenance/drift/mod.rs"]
mod drift;
#[path = "../src/release_doc.rs"]
mod release_doc;
#[path = "../src/root_intake_layout.rs"]
mod root_intake_layout;
#[path = "../src/support_matrix.rs"]
mod support_matrix;

use drift::{check_agent_drift, DriftCategory, DriftCheckError};
use harness::{fixture_root, seed_gemini_approval_artifact, seed_release_touchpoints, write_text};

#[test]
fn check_agent_drift_reports_clean_agent() {
    let fixture = fixture_root("agent-maintenance-drift-clean");
    seed_publication_inputs(&fixture);

    let report = check_agent_drift(&fixture, "gemini_cli").expect("clean report");
    assert!(report.is_clean(), "{}", report.render());
}

#[test]
fn check_agent_drift_rejects_unknown_agent() {
    let fixture = fixture_root("agent-maintenance-drift-unknown");
    seed_publication_inputs(&fixture);

    let err = check_agent_drift(&fixture, "missing-agent").expect_err("unknown agent should fail");
    assert!(
        matches!(err, DriftCheckError::Validation(message) if message.contains("missing-agent"))
    );
}

#[test]
fn check_agent_drift_reports_support_publication_mismatch() {
    let fixture = fixture_root("agent-maintenance-drift-support");
    seed_publication_inputs(&fixture);
    seed_governance_closeouts(
        &fixture,
        &[
            "agent_api.run",
            "agent_api.events",
            "agent_api.events.live",
            "agent_api.config.model.v1",
            "agent_api.session.resume.v1",
            "agent_api.session.fork.v1",
        ],
        true,
    );

    write_text(
        &fixture.join("docs/specs/unified-agent-api/support-matrix.md"),
        "# Support matrix\n\nCorrupted support publication.\n",
    );

    let report = check_agent_drift(&fixture, "opencode").expect("drift report");
    assert!(report
        .findings
        .iter()
        .any(|finding| finding.category == DriftCategory::SupportPublication));
}

#[test]
fn check_agent_drift_reports_capability_truth_mismatch() {
    let fixture = fixture_root("agent-maintenance-drift-capability");
    seed_publication_inputs(&fixture);
    seed_governance_closeouts(
        &fixture,
        &[
            "agent_api.run",
            "agent_api.events",
            "agent_api.events.live",
            "agent_api.config.model.v1",
            "agent_api.session.resume.v1",
            "agent_api.session.fork.v1",
        ],
        true,
    );

    write_text(
        &fixture.join("docs/specs/unified-agent-api/capability-matrix.md"),
        "# Capability matrix\n\nThis file is generated by `cargo run -p xtask -- capability-matrix`.\n\n## `agent_api.core`\n\n| capability id | `opencode` |\n|---|---|\n| `agent_api.run` | ✅ |\n",
    );

    let report = check_agent_drift(&fixture, "opencode").expect("drift report");
    assert!(report
        .findings
        .iter()
        .any(|finding| finding.category == DriftCategory::CapabilityPublication));
}

#[test]
fn check_agent_drift_reports_governance_doc_mismatch() {
    let fixture = fixture_root("agent-maintenance-drift-governance");
    seed_publication_inputs(&fixture);
    seed_governance_closeouts(
        &fixture,
        &["agent_api.run", "agent_api.events", "agent_api.events.live"],
        true,
    );

    let report = check_agent_drift(&fixture, "opencode").expect("drift report");
    let finding = report
        .findings
        .iter()
        .find(|finding| finding.category == DriftCategory::GovernanceDoc)
        .expect("governance finding");
    assert!(finding.surfaces.contains(
        &"docs/project_management/next/opencode-implementation/governance/seam-2-closeout.md"
            .to_string()
    ));
    assert!(finding
        .surfaces
        .contains(&"docs/specs/unified-agent-api/capability-matrix.md".to_string()));
}

#[test]
fn check_agent_drift_reports_gemini_approval_descriptor_mismatch() {
    let fixture = fixture_root("agent-maintenance-drift-gemini-approval");
    seed_publication_inputs(&fixture);

    write_text(
        &fixture.join(
            "docs/project_management/next/gemini-cli-onboarding/governance/approved-agent.toml",
        ),
        concat!(
            "artifact_version = \"1\"\n",
            "comparison_ref = \"docs/project_management/next/comparisons/gemini.md\"\n",
            "selection_mode = \"factory_validation\"\n",
            "recommended_agent_id = \"gemini_cli\"\n",
            "approved_agent_id = \"gemini_cli\"\n",
            "approval_commit = \"deadbeef\"\n",
            "approval_recorded_at = \"2026-04-21T11:23:09Z\"\n\n",
            "[descriptor]\n",
            "agent_id = \"gemini_cli\"\n",
            "display_name = \"Gemini CLI\"\n",
            "crate_path = \"crates/gemini_cli\"\n",
            "backend_module = \"crates/agent_api/src/backends/gemini_cli\"\n",
            "manifest_root = \"cli_manifests/gemini_cli\"\n",
            "package_name = \"unified-agent-api-gemini-cli\"\n",
            "canonical_targets = [\"darwin-arm64\"]\n",
            "wrapper_coverage_binding_kind = \"generated_from_wrapper_crate\"\n",
            "wrapper_coverage_source_path = \"crates/gemini_cli\"\n",
            "always_on_capabilities = [\"agent_api.run\"]\n",
            "backend_extensions = []\n",
            "support_matrix_enabled = true\n",
            "capability_matrix_enabled = true\n",
            "docs_release_track = \"crates-io\"\n",
            "onboarding_pack_prefix = \"gemini-cli-onboarding\"\n",
        ),
    );

    let report = check_agent_drift(&fixture, "gemini_cli").expect("drift report");
    let finding = report
        .findings
        .iter()
        .find(|finding| finding.category == DriftCategory::GovernanceDoc)
        .expect("governance finding");
    assert!(finding.surfaces.contains(
        &"docs/project_management/next/gemini-cli-onboarding/governance/approved-agent.toml"
            .to_string()
    ));
    assert!(finding
        .surfaces
        .contains(&"crates/xtask/data/agent_registry.toml".to_string()));
}

#[test]
fn check_agent_drift_reports_recurring_closed_governance_surface() {
    let fixture = fixture_root("agent-maintenance-drift-governance-closed");
    seed_publication_inputs(&fixture);
    seed_governance_closeouts(
        &fixture,
        &["agent_api.run", "agent_api.events", "agent_api.events.live"],
        false,
    );
    seed_cli_manifest_root(
        &fixture,
        "cli_manifests/opencode",
        &["linux-x64", "darwin-arm64", "win32-x64"],
        &[],
    );
    seed_closed_governance_maintenance(
        &fixture,
        "docs/project_management/next/opencode-implementation/governance/seam-2-closeout.md",
    );

    let report = check_agent_drift(&fixture, "opencode").expect("drift report");
    assert!(
        report
            .findings
            .iter()
            .any(|finding| finding.category == DriftCategory::GovernanceDoc),
        "{}",
        report.render()
    );
}

#[test]
fn check_agent_drift_entrypoint_exits_zero_for_clean_agent() {
    let fixture = fixture_root("agent-maintenance-drift-exit-clean");
    seed_publication_inputs(&fixture);

    let output = run_xtask_check_agent_drift(&fixture, "gemini_cli");
    assert!(
        output.status.success(),
        "stdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(String::from_utf8_lossy(&output.stdout).contains("status: clean"));
}

#[test]
fn check_agent_drift_entrypoint_exits_two_for_drift() {
    let fixture = fixture_root("agent-maintenance-drift-exit-drift");
    seed_publication_inputs(&fixture);
    seed_governance_closeouts(
        &fixture,
        &["agent_api.run", "agent_api.events", "agent_api.events.live"],
        true,
    );

    let output = run_xtask_check_agent_drift(&fixture, "opencode");
    assert_eq!(output.status.code(), Some(2));
    assert!(String::from_utf8_lossy(&output.stdout).contains("status: drift_detected"));
}

#[test]
fn check_agent_drift_entrypoint_exits_two_for_unknown_agent() {
    let fixture = fixture_root("agent-maintenance-drift-exit-unknown");
    seed_publication_inputs(&fixture);

    let output = run_xtask_check_agent_drift(&fixture, "missing-agent");
    assert_eq!(output.status.code(), Some(2));
    assert!(String::from_utf8_lossy(&output.stderr).contains("missing-agent"));
}

#[test]
fn check_agent_drift_entrypoint_exits_one_when_workspace_root_is_missing() {
    let dir = std::env::temp_dir().join(format!(
        "agent-maintenance-drift-no-workspace-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .expect("system time after unix epoch")
            .as_nanos()
    ));
    fs::create_dir_all(&dir).expect("create temp dir");

    let xtask_bin = PathBuf::from(env!("CARGO_BIN_EXE_xtask"));
    let output = Command::new(xtask_bin)
        .arg("check-agent-drift")
        .arg("--agent")
        .arg("opencode")
        .current_dir(&dir)
        .output()
        .expect("spawn xtask check-agent-drift");

    assert_eq!(output.status.code(), Some(1));
    assert!(String::from_utf8_lossy(&output.stderr).contains("could not resolve workspace root"));
}

fn seed_publication_inputs(root: &Path) {
    write_text(
        &root.join("Cargo.toml"),
        "[workspace]\nmembers = [\n  \"crates/agent_api\",\n  \"crates/codex\",\n  \"crates/claude_code\",\n  \"crates/opencode\",\n  \"crates/gemini_cli\",\n  \"crates/wrapper_events\",\n  \"crates/xtask\",\n]\n",
    );
    seed_release_touchpoints(root);
    write_text(
        &root.join("docs/specs/unified-agent-api/support-matrix.md"),
        "# Support matrix\n\nManual contract text.\n",
    );

    seed_publishable_workspace_member(root, "crates/gemini_cli", "unified-agent-api-gemini-cli");
    seed_cli_manifest_root(
        root,
        "cli_manifests/codex",
        &["x86_64-unknown-linux-musl"],
        &[(&["mcp", "list"], &["x86_64-unknown-linux-musl"])],
    );
    seed_cli_manifest_root(
        root,
        "cli_manifests/claude_code",
        &["linux-x64"],
        &[(&["mcp", "list"], &["linux-x64"])],
    );
    seed_cli_manifest_root(root, "cli_manifests/opencode", &["linux-x64"], &[]);
    seed_cli_manifest_root(root, "cli_manifests/gemini_cli", &["darwin-arm64"], &[]);

    let support_bundle =
        support_matrix::generate_publication_artifacts(root).expect("generate support publication");
    write_text(
        &root.join("cli_manifests/support_matrix/current.json"),
        &support_bundle.json,
    );
    write_text(
        &root.join("docs/specs/unified-agent-api/support-matrix.md"),
        &support_bundle.markdown,
    );

    write_text(
        &root.join("docs/specs/unified-agent-api/capability-matrix.md"),
        &default_capability_matrix_markdown(),
    );

    seed_gemini_approval_artifact(
        root,
        "docs/project_management/next/gemini-cli-onboarding/governance/approved-agent.toml",
        "gemini-cli-onboarding",
    );

    let release_doc = release_doc::render_release_doc(root).expect("render release doc");
    write_text(&root.join(release_doc::RELEASE_DOC_PATH), &release_doc);
}

fn seed_governance_closeouts(
    root: &Path,
    opencode_capabilities: &[&str],
    support_unsupported: bool,
) {
    let capability_lines = opencode_capabilities
        .iter()
        .map(|capability| format!("`{capability}`"))
        .collect::<Vec<_>>()
        .join(", ");
    write_text(
        &root.join(
            "docs/project_management/next/opencode-implementation/governance/seam-2-closeout.md",
        ),
        &format!(
            "# Closeout\n\n- capability advertisement is intentionally conservative and now matches the landed backend contract and generated capability inventory:\n  <!-- xtask-governance-check:opencode-capabilities:start -->\n  {capability_lines}\n  <!-- xtask-governance-check:opencode-capabilities:end -->\n  are the claimed OpenCode v1 capability ids under the current runtime evidence\n"
        ),
    );

    let seam3_text = if support_unsupported {
        "# Closeout\n\n- the support publication artifacts now show OpenCode as manifest-supported only where committed root evidence justifies it, while\n  <!-- xtask-governance-check:opencode-support:start -->\n  backend_support = unsupported\n  uaa_support = unsupported\n  <!-- xtask-governance-check:opencode-support:end -->\n  under the current backend evidence and pointer posture\n"
    } else {
        "# Closeout\n\n- the support publication artifacts now show OpenCode as manifest-supported only where committed root evidence justifies it, while\n  <!-- xtask-governance-check:opencode-support:start -->\n  backend_support = supported\n  uaa_support = supported\n  <!-- xtask-governance-check:opencode-support:end -->\n  under the current backend evidence and pointer posture\n"
    };
    write_text(
        &root.join(
            "docs/project_management/next/opencode-implementation/governance/seam-3-closeout.md",
        ),
        seam3_text,
    );
}

fn default_capability_matrix_markdown() -> String {
    "# Capability matrix — Unified Agent API\n\nStatus: Approved  \nApproved (UTC): 2026-02-21\n\nThis file is generated by `cargo run -p xtask -- capability-matrix`.\nCanonical target profile: `codex=x86_64-unknown-linux-musl`, `claude_code=linux-x64`; `opencode`, `gemini_cli` use the default built-in backend config.\nThis inventory documents backend capability advertising, not support or promotion status.\nDo not edit by hand.\n\n## `agent_api.core`\n\n| capability id | `claude_code` | `codex` | `gemini_cli` | `opencode` |\n|---|---|---|---|---|\n| `agent_api.events` | ✅ | ✅ | ✅ | ✅ |\n| `agent_api.run` | ✅ | ✅ | ✅ | ✅ |\n\n## `agent_api.events`\n\n| capability id | `claude_code` | `codex` | `gemini_cli` | `opencode` |\n|---|---|---|---|---|\n| `agent_api.events.live` | ✅ | ✅ | ✅ | ✅ |\n\n## `agent_api.session`\n\n| capability id | `claude_code` | `codex` | `gemini_cli` | `opencode` |\n|---|---|---|---|---|\n| `agent_api.session.fork.v1` | ✅ | ✅ | — | ✅ |\n| `agent_api.session.resume.v1` | ✅ | ✅ | — | ✅ |\n\n## `agent_api.config`\n\n| capability id | `claude_code` | `codex` | `gemini_cli` | `opencode` |\n|---|---|---|---|---|\n| `agent_api.config.model.v1` | ✅ | ✅ | ✅ | ✅ |\n".to_string()
}

fn seed_closed_governance_maintenance(root: &Path, resolved_surface: &str) {
    write_text(
        &root.join(
            "docs/project_management/next/opencode-maintenance/governance/maintenance-closeout.json",
        ),
        &serde_json::to_string_pretty(&serde_json::json!({
            "resolved_findings": [{
                "category_id": "governance_doc_drift",
                "surfaces": [resolved_surface],
            }]
        }))
        .expect("serialize maintenance closeout"),
    );
}

fn run_xtask_check_agent_drift(fixture_root: &Path, agent_id: &str) -> std::process::Output {
    let xtask_bin = PathBuf::from(env!("CARGO_BIN_EXE_xtask"));
    Command::new(xtask_bin)
        .arg("check-agent-drift")
        .arg("--agent")
        .arg(agent_id)
        .current_dir(fixture_root)
        .output()
        .expect("spawn xtask check-agent-drift")
}

fn seed_publishable_workspace_member(root: &Path, member_path: &str, package_name: &str) {
    write_text(
        &root.join(member_path).join("Cargo.toml"),
        &format!("[package]\nname = \"{package_name}\"\nversion = \"0.2.3\"\nedition = \"2021\"\n"),
    );
}

fn seed_cli_manifest_root(
    root: &Path,
    manifest_root: &str,
    canonical_targets: &[&str],
    commands: &[(&[&str], &[&str])],
) {
    let current = serde_json::json!({
        "expected_targets": canonical_targets,
        "inputs": [{
            "target_triple": canonical_targets[0],
            "binary": { "semantic_version": "1.0.0" }
        }],
        "commands": commands
            .iter()
            .map(|(path, available_on)| serde_json::json!({
                "path": path,
                "available_on": available_on,
            }))
            .collect::<Vec<_>>(),
    });
    write_text(
        &root.join(manifest_root).join("current.json"),
        &format!(
            "{}\n",
            serde_json::to_string_pretty(&current).expect("serialize current manifest")
        ),
    );

    let version = serde_json::json!({
        "semantic_version": "1.0.0",
        "status": "supported",
        "coverage": { "supported_targets": canonical_targets },
    });
    write_text(
        &root.join(manifest_root).join("versions/1.0.0.json"),
        &format!(
            "{}\n",
            serde_json::to_string_pretty(&version).expect("serialize version metadata")
        ),
    );

    for target in canonical_targets {
        write_text(
            &root
                .join(manifest_root)
                .join(format!("pointers/latest_supported/{target}.txt")),
            "1.0.0\n",
        );
        write_text(
            &root
                .join(manifest_root)
                .join(format!("pointers/latest_validated/{target}.txt")),
            "1.0.0\n",
        );
        let report = serde_json::json!({
            "inputs": { "upstream": { "targets": [target] } },
            "deltas": {
                "missing_commands": [],
                "missing_flags": [],
                "missing_args": [],
                "intentionally_unsupported": [],
                "wrapper_only_commands": [],
                "wrapper_only_flags": [],
                "wrapper_only_args": [],
            }
        });
        write_text(
            &root
                .join(manifest_root)
                .join(format!("reports/1.0.0/coverage.{target}.json")),
            &format!(
                "{}\n",
                serde_json::to_string_pretty(&report).expect("serialize report")
            ),
        );
    }
}
