#![allow(dead_code, unused_imports)]

use std::{fs, path::Path};

#[path = "support/onboard_agent_harness.rs"]
mod harness;

#[path = "../src/agent_registry.rs"]
mod agent_registry;
#[path = "../src/agent_maintenance/drift/mod.rs"]
mod drift;
#[path = "../src/release_doc.rs"]
mod release_doc;
#[path = "../src/root_intake_layout.rs"]
mod root_intake_layout;
#[path = "../src/support_matrix.rs"]
mod support_matrix;

use drift::{check_agent_drift, DriftCategory, DriftCheckError};
use harness::{fixture_root, seed_release_touchpoints, write_text};

#[test]
fn check_agent_drift_reports_clean_agent() {
    let fixture = fixture_root("agent-maintenance-drift-clean");
    seed_publication_inputs(&fixture);

    let report = check_agent_drift(&fixture, "gemini_cli").expect("clean report");
    assert!(report.is_clean(), "{}", report.render());
}

#[test]
fn check_agent_drift_rejects_unknown_agent() {
    let fixture = fixture_root("agent-maintenance-drift-unknown");
    seed_publication_inputs(&fixture);

    let err = check_agent_drift(&fixture, "missing-agent").expect_err("unknown agent should fail");
    assert!(matches!(
        err,
        DriftCheckError::UnknownAgent { agent_id } if agent_id == "missing-agent"
    ));
}

#[test]
fn check_agent_drift_reports_support_publication_mismatch() {
    let fixture = fixture_root("agent-maintenance-drift-support");
    seed_publication_inputs(&fixture);
    seed_governance_closeouts(
        &fixture,
        &[
            "agent_api.run",
            "agent_api.events",
            "agent_api.events.live",
            "agent_api.config.model.v1",
            "agent_api.session.resume.v1",
            "agent_api.session.fork.v1",
        ],
        true,
    );

    write_text(
        &fixture.join("docs/specs/unified-agent-api/support-matrix.md"),
        "# Support matrix\n\nCorrupted support publication.\n",
    );

    let report = check_agent_drift(&fixture, "opencode").expect("drift report");
    assert!(report
        .findings
        .iter()
        .any(|finding| finding.category == DriftCategory::SupportPublication));
}

#[test]
fn check_agent_drift_reports_capability_truth_mismatch() {
    let fixture = fixture_root("agent-maintenance-drift-capability");
    seed_publication_inputs(&fixture);
    seed_governance_closeouts(
        &fixture,
        &[
            "agent_api.run",
            "agent_api.events",
            "agent_api.events.live",
            "agent_api.config.model.v1",
            "agent_api.session.resume.v1",
            "agent_api.session.fork.v1",
        ],
        true,
    );

    write_text(
        &fixture.join("docs/specs/unified-agent-api/capability-matrix.md"),
        "# Capability matrix\n\nThis file is generated by `cargo run -p xtask -- capability-matrix`.\n\n## `agent_api.core`\n\n| capability id | `opencode` |\n|---|---|\n| `agent_api.run` | ✅ |\n",
    );

    let report = check_agent_drift(&fixture, "opencode").expect("drift report");
    assert!(report
        .findings
        .iter()
        .any(|finding| finding.category == DriftCategory::CapabilityPublication));
}

#[test]
fn check_agent_drift_reports_governance_doc_mismatch() {
    let fixture = fixture_root("agent-maintenance-drift-governance");
    seed_publication_inputs(&fixture);
    seed_governance_closeouts(
        &fixture,
        &["agent_api.run", "agent_api.events", "agent_api.events.live"],
        true,
    );

    let report = check_agent_drift(&fixture, "opencode").expect("drift report");
    let finding = report
        .findings
        .iter()
        .find(|finding| finding.category == DriftCategory::GovernanceDoc)
        .expect("governance finding");
    assert!(finding.surfaces.contains(
        &"docs/project_management/next/opencode-implementation/governance/seam-2-closeout.md"
            .to_string()
    ));
    assert!(finding
        .surfaces
        .contains(&"docs/specs/unified-agent-api/capability-matrix.md".to_string()));
}

#[test]
fn check_agent_drift_suppresses_closed_governance_surface() {
    let fixture = fixture_root("agent-maintenance-drift-governance-closed");
    seed_publication_inputs(&fixture);
    seed_governance_closeouts(
        &fixture,
        &["agent_api.run", "agent_api.events", "agent_api.events.live"],
        false,
    );
    seed_cli_manifest_root(
        &fixture,
        "cli_manifests/opencode",
        &["linux-x64", "darwin-arm64", "win32-x64"],
        &[],
    );
    seed_closed_governance_maintenance(
        &fixture,
        "docs/project_management/next/opencode-implementation/governance/seam-2-closeout.md",
    );

    let report = check_agent_drift(&fixture, "opencode").expect("drift report");
    assert!(
        report
            .findings
            .iter()
            .all(|finding| finding.category != DriftCategory::GovernanceDoc),
        "{}",
        report.render()
    );
}

fn seed_publication_inputs(root: &Path) {
    write_text(
        &root.join("Cargo.toml"),
        "[workspace]\nmembers = [\n  \"crates/agent_api\",\n  \"crates/codex\",\n  \"crates/claude_code\",\n  \"crates/opencode\",\n  \"crates/gemini_cli\",\n  \"crates/wrapper_events\",\n  \"crates/xtask\",\n]\n",
    );
    seed_release_touchpoints(root);
    write_text(
        &root.join("docs/specs/unified-agent-api/support-matrix.md"),
        "# Support matrix\n\nManual contract text.\n",
    );

    seed_publishable_workspace_member(root, "crates/gemini_cli", "unified-agent-api-gemini-cli");
    seed_cli_manifest_root(
        root,
        "cli_manifests/codex",
        &["x86_64-unknown-linux-musl"],
        &[(&["mcp", "list"], &["x86_64-unknown-linux-musl"])],
    );
    seed_cli_manifest_root(
        root,
        "cli_manifests/claude_code",
        &["linux-x64"],
        &[(&["mcp", "list"], &["linux-x64"])],
    );
    seed_cli_manifest_root(root, "cli_manifests/opencode", &["linux-x64"], &[]);
    seed_cli_manifest_root(root, "cli_manifests/gemini_cli", &["darwin-arm64"], &[]);

    let support_bundle =
        support_matrix::generate_publication_artifacts(root).expect("generate support publication");
    write_text(
        &root.join("cli_manifests/support_matrix/current.json"),
        &support_bundle.json,
    );
    write_text(
        &root.join("docs/specs/unified-agent-api/support-matrix.md"),
        &support_bundle.markdown,
    );

    write_text(
        &root.join("docs/specs/unified-agent-api/capability-matrix.md"),
        &default_capability_matrix_markdown(),
    );

    let release_doc = release_doc::render_release_doc(root).expect("render release doc");
    write_text(&root.join(release_doc::RELEASE_DOC_PATH), &release_doc);
}

fn seed_governance_closeouts(
    root: &Path,
    opencode_capabilities: &[&str],
    support_unsupported: bool,
) {
    let capability_lines = opencode_capabilities
        .iter()
        .map(|capability| format!("`{capability}`"))
        .collect::<Vec<_>>()
        .join(", ");
    write_text(
        &root.join(
            "docs/project_management/next/opencode-implementation/governance/seam-2-closeout.md",
        ),
        &format!(
            "# Closeout\n\n- capability advertisement is intentionally conservative and now matches the landed backend contract and generated capability inventory: {capability_lines} are the claimed OpenCode v1 capability ids under the current runtime evidence\n"
        ),
    );

    let seam3_text = if support_unsupported {
        "# Closeout\n\n- backend support and UAA support remain `unsupported` under the current backend evidence and pointer posture\n"
    } else {
        "# Closeout\n\n- support posture changed\n"
    };
    write_text(
        &root.join(
            "docs/project_management/next/opencode-implementation/governance/seam-3-closeout.md",
        ),
        seam3_text,
    );
}

fn default_capability_matrix_markdown() -> String {
    "# Capability matrix — Unified Agent API\n\nStatus: Approved  \nApproved (UTC): 2026-02-21\n\nThis file is generated by `cargo run -p xtask -- capability-matrix`.\nCanonical target profile: `codex=x86_64-unknown-linux-musl`, `claude_code=linux-x64`; `opencode`, `gemini_cli` use the default built-in backend config.\nThis inventory documents backend capability advertising, not support or promotion status.\nDo not edit by hand.\n\n## `agent_api.core`\n\n| capability id | `claude_code` | `codex` | `gemini_cli` | `opencode` |\n|---|---|---|---|---|\n| `agent_api.events` | ✅ | ✅ | ✅ | ✅ |\n| `agent_api.run` | ✅ | ✅ | ✅ | ✅ |\n\n## `agent_api.events`\n\n| capability id | `claude_code` | `codex` | `gemini_cli` | `opencode` |\n|---|---|---|---|---|\n| `agent_api.events.live` | ✅ | ✅ | ✅ | ✅ |\n\n## `agent_api.session`\n\n| capability id | `claude_code` | `codex` | `gemini_cli` | `opencode` |\n|---|---|---|---|---|\n| `agent_api.session.fork.v1` | ✅ | ✅ | — | ✅ |\n| `agent_api.session.resume.v1` | ✅ | ✅ | — | ✅ |\n\n## `agent_api.config`\n\n| capability id | `claude_code` | `codex` | `gemini_cli` | `opencode` |\n|---|---|---|---|---|\n| `agent_api.config.model.v1` | ✅ | ✅ | ✅ | ✅ |\n".to_string()
}

fn seed_closed_governance_maintenance(root: &Path, resolved_surface: &str) {
    write_text(
        &root.join(
            "docs/project_management/next/opencode-maintenance/governance/maintenance-closeout.json",
        ),
        &serde_json::to_string_pretty(&serde_json::json!({
            "resolved_findings": [{
                "category_id": "governance_doc_drift",
                "surfaces": [resolved_surface],
            }]
        }))
        .expect("serialize maintenance closeout"),
    );
}

fn seed_publishable_workspace_member(root: &Path, member_path: &str, package_name: &str) {
    write_text(
        &root.join(member_path).join("Cargo.toml"),
        &format!("[package]\nname = \"{package_name}\"\nversion = \"0.2.3\"\nedition = \"2021\"\n"),
    );
}

fn seed_cli_manifest_root(
    root: &Path,
    manifest_root: &str,
    canonical_targets: &[&str],
    commands: &[(&[&str], &[&str])],
) {
    let current = serde_json::json!({
        "expected_targets": canonical_targets,
        "inputs": [{
            "target_triple": canonical_targets[0],
            "binary": { "semantic_version": "1.0.0" }
        }],
        "commands": commands
            .iter()
            .map(|(path, available_on)| serde_json::json!({
                "path": path,
                "available_on": available_on,
            }))
            .collect::<Vec<_>>(),
    });
    write_text(
        &root.join(manifest_root).join("current.json"),
        &format!(
            "{}\n",
            serde_json::to_string_pretty(&current).expect("serialize current manifest")
        ),
    );

    let version = serde_json::json!({
        "semantic_version": "1.0.0",
        "status": "supported",
        "coverage": { "supported_targets": canonical_targets },
    });
    write_text(
        &root.join(manifest_root).join("versions/1.0.0.json"),
        &format!(
            "{}\n",
            serde_json::to_string_pretty(&version).expect("serialize version metadata")
        ),
    );

    for target in canonical_targets {
        write_text(
            &root
                .join(manifest_root)
                .join(format!("pointers/latest_supported/{target}.txt")),
            "1.0.0\n",
        );
        write_text(
            &root
                .join(manifest_root)
                .join(format!("pointers/latest_validated/{target}.txt")),
            "1.0.0\n",
        );
        let report = serde_json::json!({
            "inputs": { "upstream": { "targets": [target] } },
            "deltas": {
                "missing_commands": [],
                "missing_flags": [],
                "missing_args": [],
                "intentionally_unsupported": [],
                "wrapper_only_commands": [],
                "wrapper_only_flags": [],
                "wrapper_only_args": [],
            }
        });
        write_text(
            &root
                .join(manifest_root)
                .join(format!("reports/1.0.0/coverage.{target}.json")),
            &format!(
                "{}\n",
                serde_json::to_string_pretty(&report).expect("serialize report")
            ),
        );
    }
}
